# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: networking/v1alpha3/k8s_gateway.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='networking/v1alpha3/k8s_gateway.proto',
  package='istio.networking.v1alpha3',
  syntax='proto3',
  serialized_options=_b('Z istio.io/api/networking/v1alpha3'),
  serialized_pb=_b('\n%networking/v1alpha3/k8s_gateway.proto\x12\x19istio.networking.v1alpha3\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x14gogoproto/gogo.proto\"\"\n\x11KubernetesGateway\x12\r\n\x05\x63lass\x18\x01 \x01(\tB\"Z istio.io/api/networking/v1alpha3b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_KUBERNETESGATEWAY = _descriptor.Descriptor(
  name='KubernetesGateway',
  full_name='istio.networking.v1alpha3.KubernetesGateway',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class', full_name='istio.networking.v1alpha3.KubernetesGateway.class', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['KubernetesGateway'] = _KUBERNETESGATEWAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KubernetesGateway = _reflection.GeneratedProtocolMessageType('KubernetesGateway', (_message.Message,), {
  'DESCRIPTOR' : _KUBERNETESGATEWAY,
  '__module__' : 'networking.v1alpha3.k8s_gateway_pb2'
  # @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.KubernetesGateway)
  })
_sym_db.RegisterMessage(KubernetesGateway)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
