# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: networking/v1alpha3/k8s_http_route.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='networking/v1alpha3/k8s_http_route.proto',
  package='istio.networking.v1alpha3',
  syntax='proto3',
  serialized_options=_b('Z istio.io/api/networking/v1alpha3'),
  serialized_pb=_b('\n(networking/v1alpha3/k8s_http_route.proto\x12\x19istio.networking.v1alpha3\"f\n\x13KubernetesHTTPRoute\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x41\n\x05rules\x18\x02 \x03(\x0b\x32\x32.istio.networking.v1alpha3.KubernetesHTTPRouteRule\"u\n\x17KubernetesHTTPRouteRule\x12\x0c\n\x04path\x18\x01 \x01(\t\x12L\n\x07\x62\x61\x63kend\x18\x02 \x01(\x0b\x32;.istio.networking.v1alpha3.KubernetesHTTPRouteActionBackend\"A\n KubernetesHTTPRouteActionBackend\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x42\"Z istio.io/api/networking/v1alpha3b\x06proto3')
)




_KUBERNETESHTTPROUTE = _descriptor.Descriptor(
  name='KubernetesHTTPRoute',
  full_name='istio.networking.v1alpha3.KubernetesHTTPRoute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='istio.networking.v1alpha3.KubernetesHTTPRoute.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rules', full_name='istio.networking.v1alpha3.KubernetesHTTPRoute.rules', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=173,
)


_KUBERNETESHTTPROUTERULE = _descriptor.Descriptor(
  name='KubernetesHTTPRouteRule',
  full_name='istio.networking.v1alpha3.KubernetesHTTPRouteRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='istio.networking.v1alpha3.KubernetesHTTPRouteRule.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backend', full_name='istio.networking.v1alpha3.KubernetesHTTPRouteRule.backend', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=292,
)


_KUBERNETESHTTPROUTEACTIONBACKEND = _descriptor.Descriptor(
  name='KubernetesHTTPRouteActionBackend',
  full_name='istio.networking.v1alpha3.KubernetesHTTPRouteActionBackend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='istio.networking.v1alpha3.KubernetesHTTPRouteActionBackend.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='istio.networking.v1alpha3.KubernetesHTTPRouteActionBackend.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=359,
)

_KUBERNETESHTTPROUTE.fields_by_name['rules'].message_type = _KUBERNETESHTTPROUTERULE
_KUBERNETESHTTPROUTERULE.fields_by_name['backend'].message_type = _KUBERNETESHTTPROUTEACTIONBACKEND
DESCRIPTOR.message_types_by_name['KubernetesHTTPRoute'] = _KUBERNETESHTTPROUTE
DESCRIPTOR.message_types_by_name['KubernetesHTTPRouteRule'] = _KUBERNETESHTTPROUTERULE
DESCRIPTOR.message_types_by_name['KubernetesHTTPRouteActionBackend'] = _KUBERNETESHTTPROUTEACTIONBACKEND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KubernetesHTTPRoute = _reflection.GeneratedProtocolMessageType('KubernetesHTTPRoute', (_message.Message,), {
  'DESCRIPTOR' : _KUBERNETESHTTPROUTE,
  '__module__' : 'networking.v1alpha3.k8s_http_route_pb2'
  # @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.KubernetesHTTPRoute)
  })
_sym_db.RegisterMessage(KubernetesHTTPRoute)

KubernetesHTTPRouteRule = _reflection.GeneratedProtocolMessageType('KubernetesHTTPRouteRule', (_message.Message,), {
  'DESCRIPTOR' : _KUBERNETESHTTPROUTERULE,
  '__module__' : 'networking.v1alpha3.k8s_http_route_pb2'
  # @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.KubernetesHTTPRouteRule)
  })
_sym_db.RegisterMessage(KubernetesHTTPRouteRule)

KubernetesHTTPRouteActionBackend = _reflection.GeneratedProtocolMessageType('KubernetesHTTPRouteActionBackend', (_message.Message,), {
  'DESCRIPTOR' : _KUBERNETESHTTPROUTEACTIONBACKEND,
  '__module__' : 'networking.v1alpha3.k8s_http_route_pb2'
  # @@protoc_insertion_point(class_scope:istio.networking.v1alpha3.KubernetesHTTPRouteActionBackend)
  })
_sym_db.RegisterMessage(KubernetesHTTPRouteActionBackend)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
