// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta/v1alpha1/status.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	v1alpha1 "istio.io/api/analysis/v1alpha1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IstioStatus struct {
	// Current service state of pod.
	// More info: https://istio.io/docs/reference/config/config-status/
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	Conditions []*IstioCondition `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// Includes any errors or warnings detected by Istio's analyzers.
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	ValidationMessages []*v1alpha1.AnalysisMessageBase `protobuf:"bytes,2,rep,name=validation_messages,json=validationMessages,proto3" json:"validation_messages,omitempty"`
	// Resource Generation to which the Reconciled Condition refers.
	// When this value is not equal to the object's metadata generation, reconciled condition  calculation for the current
	// generation is still in progress.  See https://istio.io/latest/docs/reference/config/config-status/ for more info.
	// +optional
	ObservedGeneration   int64    `protobuf:"varint,3,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IstioStatus) Reset()         { *m = IstioStatus{} }
func (m *IstioStatus) String() string { return proto.CompactTextString(m) }
func (*IstioStatus) ProtoMessage()    {}
func (*IstioStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c58e523a81edc6, []int{0}
}

func (m *IstioStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IstioStatus.Unmarshal(m, b)
}
func (m *IstioStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IstioStatus.Marshal(b, m, deterministic)
}
func (m *IstioStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IstioStatus.Merge(m, src)
}
func (m *IstioStatus) XXX_Size() int {
	return xxx_messageInfo_IstioStatus.Size(m)
}
func (m *IstioStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_IstioStatus.DiscardUnknown(m)
}

var xxx_messageInfo_IstioStatus proto.InternalMessageInfo

func (m *IstioStatus) GetConditions() []*IstioCondition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *IstioStatus) GetValidationMessages() []*v1alpha1.AnalysisMessageBase {
	if m != nil {
		return m.ValidationMessages
	}
	return nil
}

func (m *IstioStatus) GetObservedGeneration() int64 {
	if m != nil {
		return m.ObservedGeneration
	}
	return 0
}

type IstioCondition struct {
	// Type is the type of the condition.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Status is the status of the condition.
	// Can be True, False, Unknown.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Last time we probed the condition.
	// +optional
	LastProbeTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_probe_time,json=lastProbeTime,proto3" json:"last_probe_time,omitempty"`
	// Last time the condition transitioned from one status to another.
	// +optional
	LastTransitionTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	// Unique, one-word, CamelCase reason for the condition's last transition.
	// +optional
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// Human-readable message indicating details about last transition.
	// +optional
	Message              string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IstioCondition) Reset()         { *m = IstioCondition{} }
func (m *IstioCondition) String() string { return proto.CompactTextString(m) }
func (*IstioCondition) ProtoMessage()    {}
func (*IstioCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c58e523a81edc6, []int{1}
}

func (m *IstioCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IstioCondition.Unmarshal(m, b)
}
func (m *IstioCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IstioCondition.Marshal(b, m, deterministic)
}
func (m *IstioCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IstioCondition.Merge(m, src)
}
func (m *IstioCondition) XXX_Size() int {
	return xxx_messageInfo_IstioCondition.Size(m)
}
func (m *IstioCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_IstioCondition.DiscardUnknown(m)
}

var xxx_messageInfo_IstioCondition proto.InternalMessageInfo

func (m *IstioCondition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IstioCondition) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *IstioCondition) GetLastProbeTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastProbeTime
	}
	return nil
}

func (m *IstioCondition) GetLastTransitionTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastTransitionTime
	}
	return nil
}

func (m *IstioCondition) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *IstioCondition) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*IstioStatus)(nil), "istio.meta.v1alpha1.IstioStatus")
	proto.RegisterType((*IstioCondition)(nil), "istio.meta.v1alpha1.IstioCondition")
}

func init() {
	proto.RegisterFile("meta/v1alpha1/status.proto", fileDescriptor_05c58e523a81edc6)
}

var fileDescriptor_05c58e523a81edc6 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x6a, 0xe2, 0x40,
	0x14, 0x25, 0xea, 0x66, 0xd9, 0x91, 0xdd, 0x85, 0x71, 0x91, 0x21, 0x2c, 0x28, 0xf6, 0xc5, 0x87,
	0x32, 0x41, 0xfb, 0x05, 0xd5, 0x87, 0x52, 0x68, 0xa1, 0xa4, 0x3e, 0x15, 0x4a, 0xb8, 0x69, 0xc6,
	0x38, 0x90, 0x64, 0x42, 0xee, 0x18, 0xf0, 0xad, 0xdf, 0xda, 0x2f, 0x29, 0x33, 0x93, 0x68, 0x2d,
	0x85, 0xbe, 0x79, 0xee, 0x3d, 0xe7, 0xdc, 0xe3, 0xc9, 0x90, 0xa0, 0x10, 0x1a, 0xc2, 0x66, 0x01,
	0x79, 0xb5, 0x83, 0x45, 0x88, 0x1a, 0xf4, 0x1e, 0x79, 0x55, 0x2b, 0xad, 0xe8, 0x48, 0xa2, 0x96,
	0x8a, 0x1b, 0x06, 0xef, 0x18, 0xc1, 0x04, 0x4a, 0xc8, 0x0f, 0x28, 0xf1, 0x24, 0x2a, 0x04, 0x22,
	0x64, 0xc2, 0xa9, 0x82, 0x49, 0xa6, 0x54, 0x96, 0x8b, 0xd0, 0xa2, 0x64, 0xbf, 0x0d, 0xb5, 0x2c,
	0x04, 0x6a, 0x28, 0xaa, 0x4f, 0x04, 0xa8, 0x64, 0xb8, 0x95, 0x22, 0x4f, 0xe3, 0x44, 0xec, 0xa0,
	0x91, 0xaa, 0x76, 0x84, 0xd9, 0x9b, 0x47, 0x86, 0xb7, 0xe6, 0xf4, 0xa3, 0x4d, 0x43, 0xd7, 0x84,
	0xbc, 0xa8, 0x32, 0x95, 0x5a, 0xaa, 0x12, 0x99, 0x37, 0xed, 0xcf, 0x87, 0xcb, 0x0b, 0xfe, 0x45,
	0x38, 0x6e, 0x55, 0xeb, 0x8e, 0x1b, 0x7d, 0x90, 0xd1, 0x67, 0x32, 0x6a, 0x20, 0x97, 0x29, 0x18,
	0x18, 0xb7, 0x91, 0x91, 0xf5, 0xac, 0xdb, 0x65, 0xeb, 0xd6, 0xfd, 0xb7, 0x93, 0xe3, 0x75, 0x3b,
	0xb9, 0x77, 0x82, 0x15, 0xa0, 0x88, 0xe8, 0xc9, 0xa8, 0x1d, 0x23, 0x0d, 0xc9, 0x48, 0x25, 0x28,
	0xea, 0x46, 0xa4, 0x71, 0x26, 0x4a, 0x51, 0xdb, 0x35, 0xeb, 0x4f, 0xbd, 0x79, 0x3f, 0xa2, 0xdd,
	0xea, 0xe6, 0xb8, 0x99, 0xbd, 0xf6, 0xc8, 0x9f, 0xf3, 0xb8, 0x94, 0x92, 0x81, 0x3e, 0x54, 0x82,
	0x79, 0x53, 0x6f, 0xfe, 0x2b, 0xb2, 0xbf, 0xe9, 0x98, 0xf8, 0xee, 0x9b, 0xb0, 0x9e, 0x9d, 0xb6,
	0x88, 0xae, 0xc8, 0xdf, 0x1c, 0x50, 0xc7, 0x55, 0xad, 0x12, 0x11, 0x9b, 0x8a, 0xed, 0xad, 0xe1,
	0x32, 0xe0, 0xae, 0x5e, 0xde, 0xf5, 0xcf, 0x37, 0x5d, 0xff, 0xd1, 0x6f, 0x23, 0x79, 0x30, 0x0a,
	0x33, 0xa3, 0x77, 0xe4, 0x9f, 0xf5, 0xd0, 0x35, 0x94, 0x68, 0x23, 0x38, 0xa3, 0xc1, 0xb7, 0x46,
	0xd4, 0xe8, 0x36, 0x47, 0x99, 0x75, 0x1b, 0x13, 0xbf, 0x16, 0x80, 0xaa, 0x64, 0x3f, 0x5c, 0x52,
	0x87, 0x28, 0x23, 0x3f, 0xdb, 0xb6, 0x99, 0x6f, 0x17, 0x1d, 0x5c, 0xfd, 0x7f, 0x0a, 0x5c, 0xed,
	0x52, 0xd9, 0xc7, 0x70, 0xf6, 0x14, 0x13, 0xdf, 0xde, 0xbd, 0x7a, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0x3f, 0xb5, 0x1b, 0xac, 0xa2, 0x02, 0x00, 0x00,
}
