// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/k8s_gateway.proto

// $schema: istio.networking.v1alpha3.KubernetesGateway
// $title: Kubernetes Gateway
// $description: Alpha
// $location: https://istio.io/docs/reference/config/networking/kubernetes-gateway.html

package v1alpha3

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using KubernetesGateway within kubernetes types, where deepcopy-gen is used.
func (in *KubernetesGateway) DeepCopyInto(out *KubernetesGateway) {
	p := proto.Clone(in).(*KubernetesGateway)
	*out = *p
}
