// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/k8s_http_route.proto

// $schema: istio.networking.v1alpha3.KubernetesHTTPRoute
// $title: Kubernetes HTTPRoute
// $description: Alpha
// $location: https://istio.io/docs/reference/config/networking/kubernetes-httproute.html

package v1alpha3

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using KubernetesHTTPRoute within kubernetes types, where deepcopy-gen is used.
func (in *KubernetesHTTPRoute) DeepCopyInto(out *KubernetesHTTPRoute) {
	p := proto.Clone(in).(*KubernetesHTTPRoute)
	*out = *p
}
