// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/k8s_gateway.proto

// $schema: istio.networking.v1alpha3.KubernetesGateway
// $title: Kubernetes Gateway
// $description: Alpha
// $location: https://istio.io/docs/reference/config/networking/kubernetes-gateway.html

package v1alpha3

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for KubernetesGateway
func (this *KubernetesGateway) MarshalJSON() ([]byte, error) {
	str, err := K8SGatewayMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KubernetesGateway
func (this *KubernetesGateway) UnmarshalJSON(b []byte) error {
	return K8SGatewayUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KubernetesGatewayListener
func (this *KubernetesGatewayListener) MarshalJSON() ([]byte, error) {
	str, err := K8SGatewayMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KubernetesGatewayListener
func (this *KubernetesGatewayListener) UnmarshalJSON(b []byte) error {
	return K8SGatewayUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	K8SGatewayMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	K8SGatewayUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
