// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/k8s_gateway.proto

// $schema: istio.networking.v1alpha3.KubernetesGateway
// $title: Kubernetes Gateway
// $description: Alpha
// $location: https://istio.io/docs/reference/config/networking/kubernetes-gateway.html

package v1alpha3

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	io "io"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// KubernetesGateway defines the Kubernetes gateway API
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.istio.io/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type KubernetesGateway struct {
	Class                string                       `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Listeners            []*KubernetesGatewayListener `protobuf:"bytes,2,rep,name=listeners,proto3" json:"listeners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *KubernetesGateway) Reset()         { *m = KubernetesGateway{} }
func (m *KubernetesGateway) String() string { return proto.CompactTextString(m) }
func (*KubernetesGateway) ProtoMessage()    {}
func (*KubernetesGateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3bc4c7c88cb1a8, []int{0}
}
func (m *KubernetesGateway) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KubernetesGateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KubernetesGateway.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KubernetesGateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesGateway.Merge(m, src)
}
func (m *KubernetesGateway) XXX_Size() int {
	return m.Size()
}
func (m *KubernetesGateway) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesGateway.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesGateway proto.InternalMessageInfo

func (m *KubernetesGateway) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *KubernetesGateway) GetListeners() []*KubernetesGatewayListener {
	if m != nil {
		return m.Listeners
	}
	return nil
}

type KubernetesGatewayListener struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocols            []string `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Routes               []string `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesGatewayListener) Reset()         { *m = KubernetesGatewayListener{} }
func (m *KubernetesGatewayListener) String() string { return proto.CompactTextString(m) }
func (*KubernetesGatewayListener) ProtoMessage()    {}
func (*KubernetesGatewayListener) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3bc4c7c88cb1a8, []int{1}
}
func (m *KubernetesGatewayListener) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KubernetesGatewayListener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KubernetesGatewayListener.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KubernetesGatewayListener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesGatewayListener.Merge(m, src)
}
func (m *KubernetesGatewayListener) XXX_Size() int {
	return m.Size()
}
func (m *KubernetesGatewayListener) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesGatewayListener.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesGatewayListener proto.InternalMessageInfo

func (m *KubernetesGatewayListener) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *KubernetesGatewayListener) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *KubernetesGatewayListener) GetProtocols() []string {
	if m != nil {
		return m.Protocols
	}
	return nil
}

func (m *KubernetesGatewayListener) GetRoutes() []string {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*KubernetesGateway)(nil), "istio.networking.v1alpha3.KubernetesGateway")
	proto.RegisterType((*KubernetesGatewayListener)(nil), "istio.networking.v1alpha3.KubernetesGatewayListener")
}

func init() {
	proto.RegisterFile("networking/v1alpha3/k8s_gateway.proto", fileDescriptor_ac3bc4c7c88cb1a8)
}

var fileDescriptor_ac3bc4c7c88cb1a8 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x3f, 0x4f, 0xfb, 0x30,
	0x14, 0x54, 0xfa, 0xef, 0xa7, 0xf8, 0x37, 0x61, 0x55, 0xc8, 0xad, 0x50, 0x88, 0x2a, 0x21, 0x65,
	0xb2, 0x05, 0x65, 0x60, 0x66, 0x61, 0x80, 0x29, 0x23, 0x4b, 0xe5, 0x34, 0xaf, 0xae, 0x55, 0x2b,
	0x2f, 0xb2, 0x9d, 0x56, 0x0c, 0x88, 0xaf, 0xc7, 0xc8, 0x47, 0x40, 0xfd, 0x24, 0x08, 0x27, 0xa5,
	0x03, 0x74, 0xbb, 0x7b, 0xef, 0xde, 0xe9, 0xce, 0x26, 0x57, 0x15, 0xf8, 0x1d, 0xda, 0x8d, 0xae,
	0x94, 0xd8, 0x5e, 0x4b, 0x53, 0xaf, 0xe5, 0x5c, 0x6c, 0xee, 0xdc, 0x42, 0x49, 0x0f, 0x3b, 0xf9,
	0xc2, 0x6b, 0x8b, 0x1e, 0xe9, 0x44, 0x3b, 0xaf, 0x91, 0x1f, 0xc5, 0xfc, 0x20, 0x9e, 0x5e, 0x2a,
	0x44, 0x65, 0x40, 0xc8, 0x5a, 0x8b, 0x95, 0x06, 0x53, 0x2e, 0x0a, 0x58, 0xcb, 0xad, 0x46, 0xdb,
	0xde, 0x4e, 0x93, 0x4e, 0x10, 0x58, 0xd1, 0xac, 0x44, 0xd9, 0x58, 0xe9, 0x35, 0x56, 0xdd, 0x7e,
	0xac, 0x50, 0x61, 0x80, 0xe2, 0x1b, 0xb5, 0xd3, 0xd9, 0x2b, 0x39, 0x7b, 0x6c, 0x0a, 0xb0, 0x15,
	0x78, 0x70, 0x0f, 0x6d, 0x18, 0x3a, 0x26, 0xc3, 0xa5, 0x91, 0xce, 0xb1, 0x28, 0x8d, 0xb2, 0x38,
	0x6f, 0x09, 0xcd, 0x49, 0x6c, 0xb4, 0xf3, 0x50, 0x81, 0x75, 0xac, 0x97, 0xf6, 0xb3, 0xff, 0x37,
	0xb7, 0xfc, 0x64, 0x60, 0xfe, 0xcb, 0xf6, 0xa9, 0x3b, 0xce, 0x8f, 0x36, 0xb3, 0x37, 0x32, 0x39,
	0xa9, 0xa3, 0x8c, 0xfc, 0x93, 0x65, 0x69, 0xe1, 0x27, 0xc8, 0x81, 0x52, 0x4a, 0x06, 0x35, 0x5a,
	0xcf, 0x7a, 0x69, 0x94, 0x0d, 0xf3, 0x80, 0xe9, 0x05, 0x89, 0x43, 0xa5, 0x25, 0x1a, 0xc7, 0xfa,
	0x69, 0x3f, 0x8b, 0xf3, 0xe3, 0x80, 0x9e, 0x93, 0x91, 0xc5, 0xc6, 0x83, 0x63, 0x83, 0xb0, 0xea,
	0xd8, 0x3d, 0x7f, 0xdf, 0x27, 0xd1, 0xc7, 0x3e, 0x89, 0x3e, 0xf7, 0x49, 0xf4, 0x9c, 0xb6, 0x75,
	0x34, 0x86, 0x67, 0xfe, 0xe3, 0xcf, 0x8a, 0x51, 0xb0, 0x9c, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0x39, 0x4e, 0x91, 0xd1, 0x01, 0x00, 0x00,
}

func (m *KubernetesGateway) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KubernetesGateway) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KubernetesGateway) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Listeners) > 0 {
		for iNdEx := len(m.Listeners) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Listeners[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintK8SGateway(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Class) > 0 {
		i -= len(m.Class)
		copy(dAtA[i:], m.Class)
		i = encodeVarintK8SGateway(dAtA, i, uint64(len(m.Class)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KubernetesGatewayListener) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KubernetesGatewayListener) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KubernetesGatewayListener) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Routes) > 0 {
		for iNdEx := len(m.Routes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Routes[iNdEx])
			copy(dAtA[i:], m.Routes[iNdEx])
			i = encodeVarintK8SGateway(dAtA, i, uint64(len(m.Routes[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Protocols) > 0 {
		for iNdEx := len(m.Protocols) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Protocols[iNdEx])
			copy(dAtA[i:], m.Protocols[iNdEx])
			i = encodeVarintK8SGateway(dAtA, i, uint64(len(m.Protocols[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Port != 0 {
		i = encodeVarintK8SGateway(dAtA, i, uint64(m.Port))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintK8SGateway(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintK8SGateway(dAtA []byte, offset int, v uint64) int {
	offset -= sovK8SGateway(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KubernetesGateway) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Class)
	if l > 0 {
		n += 1 + l + sovK8SGateway(uint64(l))
	}
	if len(m.Listeners) > 0 {
		for _, e := range m.Listeners {
			l = e.Size()
			n += 1 + l + sovK8SGateway(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *KubernetesGatewayListener) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovK8SGateway(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovK8SGateway(uint64(m.Port))
	}
	if len(m.Protocols) > 0 {
		for _, s := range m.Protocols {
			l = len(s)
			n += 1 + l + sovK8SGateway(uint64(l))
		}
	}
	if len(m.Routes) > 0 {
		for _, s := range m.Routes {
			l = len(s)
			n += 1 + l + sovK8SGateway(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovK8SGateway(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozK8SGateway(x uint64) (n int) {
	return sovK8SGateway(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KubernetesGateway) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowK8SGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KubernetesGateway: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KubernetesGateway: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Class", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowK8SGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthK8SGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Class = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Listeners", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowK8SGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthK8SGateway
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Listeners = append(m.Listeners, &KubernetesGatewayListener{})
			if err := m.Listeners[len(m.Listeners)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipK8SGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KubernetesGatewayListener) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowK8SGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KubernetesGatewayListener: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KubernetesGatewayListener: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowK8SGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthK8SGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowK8SGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocols", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowK8SGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthK8SGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Protocols = append(m.Protocols, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Routes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowK8SGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthK8SGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Routes = append(m.Routes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipK8SGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthK8SGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipK8SGateway(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowK8SGateway
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowK8SGateway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowK8SGateway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthK8SGateway
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthK8SGateway
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowK8SGateway
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipK8SGateway(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthK8SGateway
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthK8SGateway = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowK8SGateway   = fmt.Errorf("proto: integer overflow")
)
