// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Waypoint
func (this *Waypoint) MarshalJSON() ([]byte, error) {
	str, err := WaypointMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Waypoint
func (this *Waypoint) UnmarshalJSON(b []byte) error {
	return WaypointUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	WaypointMarshaler   = &jsonpb.Marshaler{}
	WaypointUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
