// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesh/v1alpha1/config.proto

// Configuration affecting the service mesh as a whole.

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	v1alpha3 "istio.io/api/networking/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Resource describes the source of configuration
type Resource int32

const (
	// Set to only receive service entries that are generated by the platform.
	// These auto generated service entries are combination of services and endpoints
	// that are generated by a specific platform e.g. k8
	Resource_SERVICE_REGISTRY Resource = 0
)

var Resource_name = map[int32]string{
	0: "SERVICE_REGISTRY",
}

var Resource_value = map[string]int32{
	"SERVICE_REGISTRY": 0,
}

func (x Resource) String() string {
	return proto.EnumName(Resource_name, int32(x))
}

func (Resource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0}
}

type MeshConfig_IngressControllerMode int32

const (
	// Unspecified Istio ingress controller.
	MeshConfig_UNSPECIFIED MeshConfig_IngressControllerMode = 0
	// Disables Istio ingress controller.
	MeshConfig_OFF MeshConfig_IngressControllerMode = 1
	// Istio ingress controller will act on ingress resources that do not
	// contain any annotation or whose annotations match the value
	// specified in the ingress_class parameter described earlier. Use this
	// mode if Istio ingress controller will be the default ingress
	// controller for the entire Kubernetes cluster.
	MeshConfig_DEFAULT MeshConfig_IngressControllerMode = 2
	// Istio ingress controller will only act on ingress resources whose
	// annotations match the value specified in the ingress_class parameter
	// described earlier. Use this mode if Istio ingress controller will be
	// a secondary ingress controller (e.g., in addition to a
	// cloud-provided ingress controller).
	MeshConfig_STRICT MeshConfig_IngressControllerMode = 3
)

var MeshConfig_IngressControllerMode_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "OFF",
	2: "DEFAULT",
	3: "STRICT",
}

var MeshConfig_IngressControllerMode_value = map[string]int32{
	"UNSPECIFIED": 0,
	"OFF":         1,
	"DEFAULT":     2,
	"STRICT":      3,
}

func (x MeshConfig_IngressControllerMode) String() string {
	return proto.EnumName(MeshConfig_IngressControllerMode_name, int32(x))
}

func (MeshConfig_IngressControllerMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 0}
}

// $hide_from_docs
type MeshConfig_AuthPolicy int32

const (
	MeshConfig_NONE       MeshConfig_AuthPolicy = 0
	MeshConfig_MUTUAL_TLS MeshConfig_AuthPolicy = 1
)

var MeshConfig_AuthPolicy_name = map[int32]string{
	0: "NONE",
	1: "MUTUAL_TLS",
}

var MeshConfig_AuthPolicy_value = map[string]int32{
	"NONE":       0,
	"MUTUAL_TLS": 1,
}

func (x MeshConfig_AuthPolicy) String() string {
	return proto.EnumName(MeshConfig_AuthPolicy_name, int32(x))
}

func (MeshConfig_AuthPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 1}
}

type MeshConfig_AccessLogEncoding int32

const (
	// text encoding for the proxy access log
	MeshConfig_TEXT MeshConfig_AccessLogEncoding = 0
	// json encoding for the proxy access log
	MeshConfig_JSON MeshConfig_AccessLogEncoding = 1
)

var MeshConfig_AccessLogEncoding_name = map[int32]string{
	0: "TEXT",
	1: "JSON",
}

var MeshConfig_AccessLogEncoding_value = map[string]int32{
	"TEXT": 0,
	"JSON": 1,
}

func (x MeshConfig_AccessLogEncoding) String() string {
	return proto.EnumName(MeshConfig_AccessLogEncoding_name, int32(x))
}

func (MeshConfig_AccessLogEncoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 2}
}

// Default Policy for upgrading http1.1 connections to http2.
type MeshConfig_H2UpgradePolicy int32

const (
	// Do not upgrade connections to http2.
	MeshConfig_DO_NOT_UPGRADE MeshConfig_H2UpgradePolicy = 0
	// Upgrade the connections to http2.
	MeshConfig_UPGRADE MeshConfig_H2UpgradePolicy = 1
)

var MeshConfig_H2UpgradePolicy_name = map[int32]string{
	0: "DO_NOT_UPGRADE",
	1: "UPGRADE",
}

var MeshConfig_H2UpgradePolicy_value = map[string]int32{
	"DO_NOT_UPGRADE": 0,
	"UPGRADE":        1,
}

func (x MeshConfig_H2UpgradePolicy) String() string {
	return proto.EnumName(MeshConfig_H2UpgradePolicy_name, int32(x))
}

func (MeshConfig_H2UpgradePolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 3}
}

type MeshConfig_OutboundTrafficPolicy_Mode int32

const (
	// outbound traffic will be restricted to services defined in the
	// service registry as well as those defined through ServiceEntries
	MeshConfig_OutboundTrafficPolicy_REGISTRY_ONLY MeshConfig_OutboundTrafficPolicy_Mode = 0
	// outbound traffic to unknown destinations will be allowed, in case
	// there are no services or ServiceEntries for the destination port
	MeshConfig_OutboundTrafficPolicy_ALLOW_ANY MeshConfig_OutboundTrafficPolicy_Mode = 1
)

var MeshConfig_OutboundTrafficPolicy_Mode_name = map[int32]string{
	0: "REGISTRY_ONLY",
	1: "ALLOW_ANY",
}

var MeshConfig_OutboundTrafficPolicy_Mode_value = map[string]int32{
	"REGISTRY_ONLY": 0,
	"ALLOW_ANY":     1,
}

func (x MeshConfig_OutboundTrafficPolicy_Mode) String() string {
	return proto.EnumName(MeshConfig_OutboundTrafficPolicy_Mode_name, int32(x))
}

func (MeshConfig_OutboundTrafficPolicy_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 0, 0}
}

// MeshConfig defines mesh-wide settings for the Istio service mesh.
type MeshConfig struct {
	// Port on which Envoy should listen for incoming connections from
	// other services. Default port is 15001.
	ProxyListenPort int32 `protobuf:"varint,4,opt,name=proxy_listen_port,json=proxyListenPort,proto3" json:"proxyListenPort,omitempty"`
	// Port on which Envoy should listen for HTTP PROXY requests if set.
	ProxyHttpPort int32 `protobuf:"varint,5,opt,name=proxy_http_port,json=proxyHttpPort,proto3" json:"proxyHttpPort,omitempty"`
	// Connection timeout used by Envoy. (MUST BE >=1ms)
	// Default timeout is 10s.
	ConnectTimeout *duration.Duration `protobuf:"bytes,6,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connectTimeout,omitempty"`
	// Automatic protocol detection uses a set of heuristics to
	// determine whether the connection is using TLS or not (on the
	// server side), as well as the application protocol being used
	// (e.g., http vs tcp). These heuristics rely on the client sending
	// the first bits of data. For server first protocols like MySQL,
	// MongoDB, etc. Envoy will timeout on the protocol detection after
	// the specified period, defaulting to non mTLS plain TCP
	// traffic. Set this field to tweak the period that Envoy will wait
	// for the client to send the first bits of data. (MUST BE >=1ms or
	// 0s to disable). Default detection timeout is 5s.
	ProtocolDetectionTimeout *duration.Duration `protobuf:"bytes,42,opt,name=protocol_detection_timeout,json=protocolDetectionTimeout,proto3" json:"protocolDetectionTimeout,omitempty"`
	// If set then set `SO_KEEPALIVE` on the socket to enable TCP Keepalives.
	TcpKeepalive *v1alpha3.ConnectionPoolSettings_TCPSettings_TcpKeepalive `protobuf:"bytes,28,opt,name=tcp_keepalive,json=tcpKeepalive,proto3" json:"tcpKeepalive,omitempty"`
	// Class of ingress resources to be processed by Istio ingress
	// controller. This corresponds to the value of
	// `kubernetes.io/ingress.class` annotation.
	IngressClass string `protobuf:"bytes,7,opt,name=ingress_class,json=ingressClass,proto3" json:"ingressClass,omitempty"`
	// Name of the Kubernetes service used for the istio ingress controller.
	// If no ingress controller is specified, the default value `istio-ingressgateway` is used.
	IngressService string `protobuf:"bytes,8,opt,name=ingress_service,json=ingressService,proto3" json:"ingressService,omitempty"`
	// Defines whether to use Istio ingress controller for annotated or all ingress resources.
	// Default mode is `STRICT`.
	IngressControllerMode MeshConfig_IngressControllerMode `protobuf:"varint,9,opt,name=ingress_controller_mode,json=ingressControllerMode,proto3,enum=istio.mesh.v1alpha1.MeshConfig_IngressControllerMode" json:"ingressControllerMode,omitempty"`
	// Defines which gateway deployment to use as the Ingress controller. This field corresponds to
	// the Gateway.selector field, and will be set as `istio: INGRESS_SELECTOR`.
	// By default, `ingressgateway` is used, which will select the default IngressGateway as it has the
	// `istio: ingressgateway` labels.
	// It is recommended that this is the same value as ingress_service.
	IngressSelector string `protobuf:"bytes,52,opt,name=ingress_selector,json=ingressSelector,proto3" json:"ingressSelector,omitempty"`
	// Flag to control generation of trace spans and request IDs.
	// Requires a trace span collector defined in the proxy configuration.
	EnableTracing bool `protobuf:"varint,12,opt,name=enable_tracing,json=enableTracing,proto3" json:"enableTracing,omitempty"`
	// File address for the proxy access log (e.g. /dev/stdout).
	// Empty value disables access logging.
	AccessLogFile string `protobuf:"bytes,13,opt,name=access_log_file,json=accessLogFile,proto3" json:"accessLogFile,omitempty"`
	// Format for the proxy access log
	// Empty value results in proxy's default access log format
	AccessLogFormat string `protobuf:"bytes,24,opt,name=access_log_format,json=accessLogFormat,proto3" json:"accessLogFormat,omitempty"`
	// Encoding for the proxy access log (`TEXT` or `JSON`).
	// Default value is `TEXT`.
	AccessLogEncoding MeshConfig_AccessLogEncoding `protobuf:"varint,27,opt,name=access_log_encoding,json=accessLogEncoding,proto3,enum=istio.mesh.v1alpha1.MeshConfig_AccessLogEncoding" json:"accessLogEncoding,omitempty"`
	// This flag enables Envoy's gRPC Access Log Service.
	// See [Access Log Service](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/accesslog/v2/als.proto)
	// for details about Envoy's gRPC Access Log Service API.
	// Default value is `false`.
	EnableEnvoyAccessLogService bool `protobuf:"varint,40,opt,name=enable_envoy_access_log_service,json=enableEnvoyAccessLogService,proto3" json:"enableEnvoyAccessLogService,omitempty"`
	// This flag disables Envoy Listener logs.
	// See [Listener Access Log](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-access-log)
	// Istio Enables Envoy's listener access logs on "NoRoute" response flag.
	// Default value is `false`.
	DisableEnvoyListenerLog bool `protobuf:"varint,56,opt,name=disable_envoy_listener_log,json=disableEnvoyListenerLog,proto3" json:"disableEnvoyListenerLog,omitempty"`
	// Default proxy config used by gateway and sidecars.
	// In case of Kubernetes, the proxy config is applied once during the injection process,
	// and remain constant for the duration of the pod. The rest of the mesh config can be changed
	// at runtime and config gets distributed dynamically.
	// On Kubernetes, this can be overridden on individual pods with the `proxy.istio.io/config` annotation.
	DefaultConfig *ProxyConfig `protobuf:"bytes,14,opt,name=default_config,json=defaultConfig,proto3" json:"defaultConfig,omitempty"`
	// Set the default behavior of the sidecar for handling outbound
	// traffic from the application.  If your application uses one or
	// more external services that are not known apriori, setting the
	// policy to `ALLOW_ANY` will cause the sidecars to route any unknown
	// traffic originating from the application to its requested
	// destination. Users are strongly encouraged to use ServiceEntries
	// to explicitly declare any external dependencies, instead of using
	// `ALLOW_ANY`, so that traffic to these services can be
	// monitored. Can be overridden at a Sidecar level by setting the
	// `OutboundTrafficPolicy` in the [Sidecar
	// API](https://istio.io/docs/reference/config/networking/sidecar/#OutboundTrafficPolicy).
	// Default mode is `ALLOW_ANY` which means outbound traffic to unknown destinations will be allowed.
	OutboundTrafficPolicy *MeshConfig_OutboundTrafficPolicy `protobuf:"bytes,17,opt,name=outbound_traffic_policy,json=outboundTrafficPolicy,proto3" json:"outboundTrafficPolicy,omitempty"`
	// ConfigSource describes a source of configuration data for networking
	// rules, and other Istio configuration artifacts. Multiple data sources
	// can be configured for a single control plane.
	ConfigSources []*ConfigSource `protobuf:"bytes,22,rep,name=config_sources,json=configSources,proto3" json:"configSources,omitempty"`
	// This flag is used to enable mutual `TLS` automatically for service to service communication
	// within the mesh, default true.
	// If set to true, and a given service does not have a corresponding `DestinationRule` configured,
	// or its `DestinationRule` does not have ClientTLSSettings specified, Istio configures client side
	// TLS configuration appropriately. More specifically,
	// If the upstream authentication policy is in `STRICT` mode, use Istio provisioned certificate
	// for mutual `TLS` to connect to upstream.
	// If upstream service is in plain text mode, use plain text.
	// If the upstream authentication policy is in PERMISSIVE mode, Istio configures clients to use
	// mutual `TLS` when server sides are capable of accepting mutual `TLS` traffic.
	// If service `DestinationRule` exists and has `ClientTLSSettings` specified, that is always used instead.
	EnableAutoMtls *wrappers.BoolValue `protobuf:"bytes,43,opt,name=enable_auto_mtls,json=enableAutoMtls,proto3" json:"enableAutoMtls,omitempty"`
	// The trust domain corresponds to the trust root of a system.
	// Refer to [SPIFFE-ID](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md#21-trust-domain)
	TrustDomain string `protobuf:"bytes,26,opt,name=trust_domain,json=trustDomain,proto3" json:"trustDomain,omitempty"`
	// The trust domain aliases represent the aliases of `trust_domain`.
	// For example, if we have
	// ```yaml
	// trustDomain: td1
	// trustDomainAliases: ["td2", "td3"]
	// ```
	// Any service with the identity `td1/ns/foo/sa/a-service-account`, `td2/ns/foo/sa/a-service-account`,
	// or `td3/ns/foo/sa/a-service-account` will be treated the same in the Istio mesh.
	TrustDomainAliases []string `protobuf:"bytes,46,rep,name=trust_domain_aliases,json=trustDomainAliases,proto3" json:"trustDomainAliases,omitempty"`
	// The extra root certificates for workload-to-workload communication.
	// The plugin certificates (the 'cacerts' secret) or self-signed certificates (the 'istio-ca-secret' secret)
	// are automatically added by Istiod.
	// The CA certificate that signs the workload certificates is automatically added by Istio Agent.
	CaCertificates []*MeshConfig_CertificateData `protobuf:"bytes,58,rep,name=ca_certificates,json=caCertificates,proto3" json:"caCertificates,omitempty"`
	// The default value for the ServiceEntry.export_to field and services
	// imported through container registry integrations, e.g. this applies to
	// Kubernetes Service resources. The value is a list of namespace names and
	// reserved namespace aliases. The allowed namespace aliases are:
	// ```
	// * - All Namespaces
	// . - Current Namespace
	// ~ - No Namespace
	// ```
	// If not set the system will use "*" as the default value which implies that
	// services are exported to all namespaces.
	//
	// `All namespaces` is a reasonable default for implementations that don't
	// need to restrict access or visibility of services across namespace
	// boundaries. If that requirement is present it is generally good practice to
	// make the default `Current namespace` so that services are only visible
	// within their own namespaces by default. Operators can then expand the
	// visibility of services to other namespaces as needed. Use of `No Namespace`
	// is expected to be rare but can have utility for deployments where
	// dependency management needs to be precise even within the scope of a single
	// namespace.
	//
	// For further discussion see the reference documentation for `ServiceEntry`,
	// `Sidecar`, and `Gateway`.
	DefaultServiceExportTo []string `protobuf:"bytes,31,rep,name=default_service_export_to,json=defaultServiceExportTo,proto3" json:"defaultServiceExportTo,omitempty"`
	// The default value for the VirtualService.export_to field. Has the same
	// syntax as `default_service_export_to`.
	//
	// If not set the system will use "*" as the default value which implies that
	// virtual services are exported to all namespaces
	DefaultVirtualServiceExportTo []string `protobuf:"bytes,32,rep,name=default_virtual_service_export_to,json=defaultVirtualServiceExportTo,proto3" json:"defaultVirtualServiceExportTo,omitempty"`
	// The default value for the `DestinationRule.export_to` field. Has the same
	// syntax as `default_service_export_to`.
	//
	// If not set the system will use "*" as the default value which implies that
	// destination rules are exported to all namespaces
	DefaultDestinationRuleExportTo []string `protobuf:"bytes,33,rep,name=default_destination_rule_export_to,json=defaultDestinationRuleExportTo,proto3" json:"defaultDestinationRuleExportTo,omitempty"`
	// The namespace to treat as the administrative root namespace for
	// Istio configuration. When processing a leaf namespace Istio will search for
	// declarations in that namespace first and if none are found it will
	// search in the root namespace. Any matching declaration found in the root
	// namespace is processed as if it were declared in the leaf namespace.
	//
	// The precise semantics of this processing are documented on each resource
	// type.
	RootNamespace string `protobuf:"bytes,34,opt,name=root_namespace,json=rootNamespace,proto3" json:"rootNamespace,omitempty"`
	// Locality based load balancing distribution or failover settings.
	LocalityLbSetting *v1alpha3.LocalityLoadBalancerSetting `protobuf:"bytes,35,opt,name=locality_lb_setting,json=localityLbSetting,proto3" json:"localityLbSetting,omitempty"`
	// Configures DNS refresh rate for Envoy clusters of type `STRICT_DNS`
	// Default refresh rate is `5s`.
	DnsRefreshRate *duration.Duration `protobuf:"bytes,36,opt,name=dns_refresh_rate,json=dnsRefreshRate,proto3" json:"dnsRefreshRate,omitempty"`
	// Specify if http1.1 connections should be upgraded to http2 by default.
	// if sidecar is installed on all pods in the mesh, then this should be set to `UPGRADE`.
	// If one or more services or namespaces do not have sidecar(s), then this should be set to `DO_NOT_UPGRADE`.
	// It can be enabled by destination using the `destinationRule.trafficPolicy.connectionPool.http.h2UpgradePolicy` override.
	H2UpgradePolicy MeshConfig_H2UpgradePolicy `protobuf:"varint,41,opt,name=h2_upgrade_policy,json=h2UpgradePolicy,proto3,enum=istio.mesh.v1alpha1.MeshConfig_H2UpgradePolicy" json:"h2UpgradePolicy,omitempty"`
	// Name to be used while emitting statistics for inbound clusters. The same pattern is used while computing stat prefix for
	// network filters like TCP and Redis.
	// By default, Istio emits statistics with the pattern `inbound|<port>|<port-name>|<service-FQDN>`.
	// For example `inbound|7443|grpc-reviews|reviews.prod.svc.cluster.local`. This can be used to override that pattern.
	//
	// A Pattern can be composed of various pre-defined variables. The following variables are supported.
	//
	// - `%SERVICE%` - Will be substituted with name of the service.
	// - `%SERVICE_FQDN%` - Will be substituted with FQDN of the service.
	// - `%SERVICE_PORT%` - Will be substituted with port of the service.
	// - `%SERVICE_PORT_NAME%` - Will be substituted with port name of the service.
	//
	// Following are some examples of supported patterns for reviews:
	//
	// - `%SERVICE_FQDN%_%SERVICE_PORT%` will use reviews.prod.svc.cluster.local_7443 as the stats name.
	// - `%SERVICE%` will use reviews.prod as the stats name.
	InboundClusterStatName string `protobuf:"bytes,44,opt,name=inbound_cluster_stat_name,json=inboundClusterStatName,proto3" json:"inboundClusterStatName,omitempty"`
	// Name to be used while emitting statistics for outbound clusters. The same pattern is used while computing stat prefix for
	// network filters like TCP and Redis.
	// By default, Istio emits statistics with the pattern `outbound|<port>|<subsetname>|<service-FQDN>`.
	// For example `outbound|8080|v2|reviews.prod.svc.cluster.local`. This can be used to override that pattern.
	//
	// A Pattern can be composed of various pre-defined variables. The following variables are supported.
	//
	// - `%SERVICE%` - Will be substituted with name of the service.
	// - `%SERVICE_FQDN%` - Will be substituted with FQDN of the service.
	// - `%SERVICE_PORT%` - Will be substituted with port of the service.
	// - `%SERVICE_PORT_NAME%` - Will be substituted with port name of the service.
	// - `%SUBSET_NAME%` - Will be substituted with subset.
	//
	// Following are some examples of supported patterns for reviews:
	//
	// - `%SERVICE_FQDN%_%SERVICE_PORT%` will use `reviews.prod.svc.cluster.local_7443` as the stats name.
	// - `%SERVICE%` will use reviews.prod as the stats name.
	OutboundClusterStatName string `protobuf:"bytes,45,opt,name=outbound_cluster_stat_name,json=outboundClusterStatName,proto3" json:"outboundClusterStatName,omitempty"`
	// Configure the provision of certificates.
	Certificates []*Certificate `protobuf:"bytes,47,rep,name=certificates,proto3" json:"certificates,omitempty"`
	// Set configuration for Thrift protocol
	ThriftConfig *MeshConfig_ThriftConfig `protobuf:"bytes,49,opt,name=thrift_config,json=thriftConfig,proto3" json:"thriftConfig,omitempty"`
	// $hide_from_docs
	// Settings to be applied to select services.
	ServiceSettings []*MeshConfig_ServiceSettings `protobuf:"bytes,50,rep,name=service_settings,json=serviceSettings,proto3" json:"serviceSettings,omitempty"`
	// If enabled, Istio agent will merge metrics exposed by the application with metrics from Envoy
	// and Istio agent. The sidecar injection will replace `prometheus.io` annotations present on the pod
	// and redirect them towards Istio agent, which will then merge metrics of from the application with Istio metrics.
	// This relies on the annotations `prometheus.io/scrape`, `prometheus.io/port`, and
	// `prometheus.io/path` annotations.
	// If you are running a separately managed Envoy with an Istio sidecar, this may cause issues, as the metrics will collide.
	// In this case, it is recommended to disable aggregation on that deployment with the
	// `prometheus.istio.io/merge-metrics: "false"` annotation.
	// If not specified, this will be enabled by default.
	EnablePrometheusMerge *wrappers.BoolValue `protobuf:"bytes,51,opt,name=enable_prometheus_merge,json=enablePrometheusMerge,proto3" json:"enablePrometheusMerge,omitempty"`
	// `VerifyCertificateAtClient` sets the mesh global default for peer certificate validation
	// at the client-side proxy when `SIMPLE` TLS or `MUTUAL` TLS (non `ISTIO_MUTUAL`) origination
	// modes are used. This setting can be overridden at the host level via DestinationRule API.
	// By default, `VerifyCertificateAtClient` is `true`.
	//
	// `CaCertificates`: If set, proxy verifies CA signature based on given CaCertificates. If unset,
	// and VerifyCertificateAtClient is true, proxy uses default System CA bundle. If unset and
	// `VerifyCertificateAtClient` is false, proxy will not verify the CA.
	//
	// `SubjectAltNames`: If set, proxy verifies subject alt names are present in the SAN. If unset,
	// and `VerifyCertificateAtClient` is true, proxy uses host in destination rule to verify the SANs.
	// If unset, and `VerifyCertificateAtClient` is false, proxy does not verify SANs.
	//
	// For SAN, client-side proxy will exact match host in `DestinationRule` as well as one level
	// wildcard if the specified host in DestinationRule doesn't contain a wildcard.
	// For example, if the host in `DestinationRule` is `x.y.com`, client-side proxy will
	// match either `x.y.com` or `*.y.com` for the SAN in the presented server certificate.
	// For wildcard host name in DestinationRule, client-side proxy will do a suffix match. For example,
	// if host is `*.x.y.com`, client-side proxy will verify the presented server certificate SAN matches
	// ``.x.y.com` suffix.
	VerifyCertificateAtClient *wrappers.BoolValue `protobuf:"bytes,54,opt,name=verify_certificate_at_client,json=verifyCertificateAtClient,proto3" json:"verifyCertificateAtClient,omitempty"`
	// $hide_from_docs
	// If specified, Istiod will authorize and forward the CSRs from the workloads to the specified external CA
	// using the Istio CA gRPC API.
	Ca *MeshConfig_CA `protobuf:"bytes,55,opt,name=ca,proto3" json:"ca,omitempty"`
	// Defines a list of extension providers that extend Istio's functionality. For example, the AuthorizationPolicy
	// can be used with an extension provider to delegate the authorization decision to a custom authorization system.
	ExtensionProviders []*MeshConfig_ExtensionProvider `protobuf:"bytes,57,rep,name=extension_providers,json=extensionProviders,proto3" json:"extensionProviders,omitempty"`
	// A list of Kubernetes selectors that specify the set of namespaces that Istio considers when
	// computing configuration updates for sidecars. This can be used to reduce Istio's computational load
	// by limiting the number of entities (including services, pods, and endpoints) that are watched and processed.
	// If omitted, Istio will use the default behavior of processing all namespaces in the cluster.
	// Elements in the list are disjunctive (OR semantics), i.e. a namespace will be included if it matches any selector.
	// The following example selects any namespace with either labels `env: prod` and `region: us-east1`,
	// or with label `app` equal to `cassandra` or `spark`.
	// ```yaml
	// discoverySelectors:
	//  - matchLabels:
	//      env: prod
	//      region: us-east1
	//  - matchExpressions:
	//    - key: app
	//      operator: In
	//      values:
	//        - cassandra
	//        - spark
	// ```
	// Refer to the [kubernetes selector docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors)
	// for additional detail on selector semantics.
	DiscoverySelectors   []*v1.LabelSelector `protobuf:"bytes,59,rep,name=discovery_selectors,json=discoverySelectors,proto3" json:"discoverySelectors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MeshConfig) Reset()         { *m = MeshConfig{} }
func (m *MeshConfig) String() string { return proto.CompactTextString(m) }
func (*MeshConfig) ProtoMessage()    {}
func (*MeshConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0}
}

func (m *MeshConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig.Unmarshal(m, b)
}
func (m *MeshConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig.Marshal(b, m, deterministic)
}
func (m *MeshConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig.Merge(m, src)
}
func (m *MeshConfig) XXX_Size() int {
	return xxx_messageInfo_MeshConfig.Size(m)
}
func (m *MeshConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig proto.InternalMessageInfo

func (m *MeshConfig) GetProxyListenPort() int32 {
	if m != nil {
		return m.ProxyListenPort
	}
	return 0
}

func (m *MeshConfig) GetProxyHttpPort() int32 {
	if m != nil {
		return m.ProxyHttpPort
	}
	return 0
}

func (m *MeshConfig) GetConnectTimeout() *duration.Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

func (m *MeshConfig) GetProtocolDetectionTimeout() *duration.Duration {
	if m != nil {
		return m.ProtocolDetectionTimeout
	}
	return nil
}

func (m *MeshConfig) GetTcpKeepalive() *v1alpha3.ConnectionPoolSettings_TCPSettings_TcpKeepalive {
	if m != nil {
		return m.TcpKeepalive
	}
	return nil
}

func (m *MeshConfig) GetIngressClass() string {
	if m != nil {
		return m.IngressClass
	}
	return ""
}

func (m *MeshConfig) GetIngressService() string {
	if m != nil {
		return m.IngressService
	}
	return ""
}

func (m *MeshConfig) GetIngressControllerMode() MeshConfig_IngressControllerMode {
	if m != nil {
		return m.IngressControllerMode
	}
	return MeshConfig_UNSPECIFIED
}

func (m *MeshConfig) GetIngressSelector() string {
	if m != nil {
		return m.IngressSelector
	}
	return ""
}

func (m *MeshConfig) GetEnableTracing() bool {
	if m != nil {
		return m.EnableTracing
	}
	return false
}

func (m *MeshConfig) GetAccessLogFile() string {
	if m != nil {
		return m.AccessLogFile
	}
	return ""
}

func (m *MeshConfig) GetAccessLogFormat() string {
	if m != nil {
		return m.AccessLogFormat
	}
	return ""
}

func (m *MeshConfig) GetAccessLogEncoding() MeshConfig_AccessLogEncoding {
	if m != nil {
		return m.AccessLogEncoding
	}
	return MeshConfig_TEXT
}

func (m *MeshConfig) GetEnableEnvoyAccessLogService() bool {
	if m != nil {
		return m.EnableEnvoyAccessLogService
	}
	return false
}

func (m *MeshConfig) GetDisableEnvoyListenerLog() bool {
	if m != nil {
		return m.DisableEnvoyListenerLog
	}
	return false
}

func (m *MeshConfig) GetDefaultConfig() *ProxyConfig {
	if m != nil {
		return m.DefaultConfig
	}
	return nil
}

func (m *MeshConfig) GetOutboundTrafficPolicy() *MeshConfig_OutboundTrafficPolicy {
	if m != nil {
		return m.OutboundTrafficPolicy
	}
	return nil
}

func (m *MeshConfig) GetConfigSources() []*ConfigSource {
	if m != nil {
		return m.ConfigSources
	}
	return nil
}

func (m *MeshConfig) GetEnableAutoMtls() *wrappers.BoolValue {
	if m != nil {
		return m.EnableAutoMtls
	}
	return nil
}

func (m *MeshConfig) GetTrustDomain() string {
	if m != nil {
		return m.TrustDomain
	}
	return ""
}

func (m *MeshConfig) GetTrustDomainAliases() []string {
	if m != nil {
		return m.TrustDomainAliases
	}
	return nil
}

func (m *MeshConfig) GetCaCertificates() []*MeshConfig_CertificateData {
	if m != nil {
		return m.CaCertificates
	}
	return nil
}

func (m *MeshConfig) GetDefaultServiceExportTo() []string {
	if m != nil {
		return m.DefaultServiceExportTo
	}
	return nil
}

func (m *MeshConfig) GetDefaultVirtualServiceExportTo() []string {
	if m != nil {
		return m.DefaultVirtualServiceExportTo
	}
	return nil
}

func (m *MeshConfig) GetDefaultDestinationRuleExportTo() []string {
	if m != nil {
		return m.DefaultDestinationRuleExportTo
	}
	return nil
}

func (m *MeshConfig) GetRootNamespace() string {
	if m != nil {
		return m.RootNamespace
	}
	return ""
}

func (m *MeshConfig) GetLocalityLbSetting() *v1alpha3.LocalityLoadBalancerSetting {
	if m != nil {
		return m.LocalityLbSetting
	}
	return nil
}

func (m *MeshConfig) GetDnsRefreshRate() *duration.Duration {
	if m != nil {
		return m.DnsRefreshRate
	}
	return nil
}

func (m *MeshConfig) GetH2UpgradePolicy() MeshConfig_H2UpgradePolicy {
	if m != nil {
		return m.H2UpgradePolicy
	}
	return MeshConfig_DO_NOT_UPGRADE
}

func (m *MeshConfig) GetInboundClusterStatName() string {
	if m != nil {
		return m.InboundClusterStatName
	}
	return ""
}

func (m *MeshConfig) GetOutboundClusterStatName() string {
	if m != nil {
		return m.OutboundClusterStatName
	}
	return ""
}

func (m *MeshConfig) GetCertificates() []*Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func (m *MeshConfig) GetThriftConfig() *MeshConfig_ThriftConfig {
	if m != nil {
		return m.ThriftConfig
	}
	return nil
}

func (m *MeshConfig) GetServiceSettings() []*MeshConfig_ServiceSettings {
	if m != nil {
		return m.ServiceSettings
	}
	return nil
}

func (m *MeshConfig) GetEnablePrometheusMerge() *wrappers.BoolValue {
	if m != nil {
		return m.EnablePrometheusMerge
	}
	return nil
}

func (m *MeshConfig) GetVerifyCertificateAtClient() *wrappers.BoolValue {
	if m != nil {
		return m.VerifyCertificateAtClient
	}
	return nil
}

func (m *MeshConfig) GetCa() *MeshConfig_CA {
	if m != nil {
		return m.Ca
	}
	return nil
}

func (m *MeshConfig) GetExtensionProviders() []*MeshConfig_ExtensionProvider {
	if m != nil {
		return m.ExtensionProviders
	}
	return nil
}

func (m *MeshConfig) GetDiscoverySelectors() []*v1.LabelSelector {
	if m != nil {
		return m.DiscoverySelectors
	}
	return nil
}

type MeshConfig_OutboundTrafficPolicy struct {
	Mode                 MeshConfig_OutboundTrafficPolicy_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=istio.mesh.v1alpha1.MeshConfig_OutboundTrafficPolicy_Mode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *MeshConfig_OutboundTrafficPolicy) Reset()         { *m = MeshConfig_OutboundTrafficPolicy{} }
func (m *MeshConfig_OutboundTrafficPolicy) String() string { return proto.CompactTextString(m) }
func (*MeshConfig_OutboundTrafficPolicy) ProtoMessage()    {}
func (*MeshConfig_OutboundTrafficPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 0}
}

func (m *MeshConfig_OutboundTrafficPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_OutboundTrafficPolicy.Unmarshal(m, b)
}
func (m *MeshConfig_OutboundTrafficPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_OutboundTrafficPolicy.Marshal(b, m, deterministic)
}
func (m *MeshConfig_OutboundTrafficPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_OutboundTrafficPolicy.Merge(m, src)
}
func (m *MeshConfig_OutboundTrafficPolicy) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_OutboundTrafficPolicy.Size(m)
}
func (m *MeshConfig_OutboundTrafficPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_OutboundTrafficPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_OutboundTrafficPolicy proto.InternalMessageInfo

func (m *MeshConfig_OutboundTrafficPolicy) GetMode() MeshConfig_OutboundTrafficPolicy_Mode {
	if m != nil {
		return m.Mode
	}
	return MeshConfig_OutboundTrafficPolicy_REGISTRY_ONLY
}

type MeshConfig_CertificateData struct {
	// Types that are valid to be assigned to CertificateData:
	//	*MeshConfig_CertificateData_Pem
	//	*MeshConfig_CertificateData_SpiffeBundleUrl
	CertificateData      isMeshConfig_CertificateData_CertificateData `protobuf_oneof:"certificate_data"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *MeshConfig_CertificateData) Reset()         { *m = MeshConfig_CertificateData{} }
func (m *MeshConfig_CertificateData) String() string { return proto.CompactTextString(m) }
func (*MeshConfig_CertificateData) ProtoMessage()    {}
func (*MeshConfig_CertificateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 1}
}

func (m *MeshConfig_CertificateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_CertificateData.Unmarshal(m, b)
}
func (m *MeshConfig_CertificateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_CertificateData.Marshal(b, m, deterministic)
}
func (m *MeshConfig_CertificateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_CertificateData.Merge(m, src)
}
func (m *MeshConfig_CertificateData) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_CertificateData.Size(m)
}
func (m *MeshConfig_CertificateData) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_CertificateData.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_CertificateData proto.InternalMessageInfo

type isMeshConfig_CertificateData_CertificateData interface {
	isMeshConfig_CertificateData_CertificateData()
}

type MeshConfig_CertificateData_Pem struct {
	Pem string `protobuf:"bytes,1,opt,name=pem,proto3,oneof"`
}

type MeshConfig_CertificateData_SpiffeBundleUrl struct {
	SpiffeBundleUrl string `protobuf:"bytes,2,opt,name=spiffe_bundle_url,json=spiffeBundleUrl,proto3,oneof"`
}

func (*MeshConfig_CertificateData_Pem) isMeshConfig_CertificateData_CertificateData() {}

func (*MeshConfig_CertificateData_SpiffeBundleUrl) isMeshConfig_CertificateData_CertificateData() {}

func (m *MeshConfig_CertificateData) GetCertificateData() isMeshConfig_CertificateData_CertificateData {
	if m != nil {
		return m.CertificateData
	}
	return nil
}

func (m *MeshConfig_CertificateData) GetPem() string {
	if x, ok := m.GetCertificateData().(*MeshConfig_CertificateData_Pem); ok {
		return x.Pem
	}
	return ""
}

func (m *MeshConfig_CertificateData) GetSpiffeBundleUrl() string {
	if x, ok := m.GetCertificateData().(*MeshConfig_CertificateData_SpiffeBundleUrl); ok {
		return x.SpiffeBundleUrl
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MeshConfig_CertificateData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MeshConfig_CertificateData_Pem)(nil),
		(*MeshConfig_CertificateData_SpiffeBundleUrl)(nil),
	}
}

type MeshConfig_ThriftConfig struct {
	// Specify thrift rate limit service URL. If pilot has thrift protocol support enabled,
	// this will enable the rate limit service for destinations that have matching rate
	// limit configurations.
	RateLimitUrl string `protobuf:"bytes,1,opt,name=rate_limit_url,json=rateLimitUrl,proto3" json:"rateLimitUrl,omitempty"`
	// Specify thrift rate limit service timeout, in milliseconds. Default is `50ms`
	RateLimitTimeout     *duration.Duration `protobuf:"bytes,2,opt,name=rate_limit_timeout,json=rateLimitTimeout,proto3" json:"rateLimitTimeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MeshConfig_ThriftConfig) Reset()         { *m = MeshConfig_ThriftConfig{} }
func (m *MeshConfig_ThriftConfig) String() string { return proto.CompactTextString(m) }
func (*MeshConfig_ThriftConfig) ProtoMessage()    {}
func (*MeshConfig_ThriftConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 2}
}

func (m *MeshConfig_ThriftConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_ThriftConfig.Unmarshal(m, b)
}
func (m *MeshConfig_ThriftConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_ThriftConfig.Marshal(b, m, deterministic)
}
func (m *MeshConfig_ThriftConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_ThriftConfig.Merge(m, src)
}
func (m *MeshConfig_ThriftConfig) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_ThriftConfig.Size(m)
}
func (m *MeshConfig_ThriftConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_ThriftConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_ThriftConfig proto.InternalMessageInfo

func (m *MeshConfig_ThriftConfig) GetRateLimitUrl() string {
	if m != nil {
		return m.RateLimitUrl
	}
	return ""
}

func (m *MeshConfig_ThriftConfig) GetRateLimitTimeout() *duration.Duration {
	if m != nil {
		return m.RateLimitTimeout
	}
	return nil
}

// $hide_from_docs
// Settings to be applied to select services.
//
// For example, the following configures all services in namespace "foo" as well as the
// "bar" service in namespace "baz" to be considered cluster-local:
//
// ```yaml
// serviceSettings:
//   - settings:
//       cluster_local: true
//     hosts:
//       - "*.foo.svc.cluster.local"
//       - "bar.baz.svc.cluster.local"
// ```
type MeshConfig_ServiceSettings struct {
	// The settings to apply to the selected services.
	Settings *MeshConfig_ServiceSettings_Settings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// The services to which the Settings should be applied. Services are selected using the hostname
	// matching rules used by DestinationRule.
	//
	// For example: foo.bar.svc.cluster.local, *.baz.svc.cluster.local
	Hosts                []string `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshConfig_ServiceSettings) Reset()         { *m = MeshConfig_ServiceSettings{} }
func (m *MeshConfig_ServiceSettings) String() string { return proto.CompactTextString(m) }
func (*MeshConfig_ServiceSettings) ProtoMessage()    {}
func (*MeshConfig_ServiceSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 3}
}

func (m *MeshConfig_ServiceSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_ServiceSettings.Unmarshal(m, b)
}
func (m *MeshConfig_ServiceSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_ServiceSettings.Marshal(b, m, deterministic)
}
func (m *MeshConfig_ServiceSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_ServiceSettings.Merge(m, src)
}
func (m *MeshConfig_ServiceSettings) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_ServiceSettings.Size(m)
}
func (m *MeshConfig_ServiceSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_ServiceSettings.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_ServiceSettings proto.InternalMessageInfo

func (m *MeshConfig_ServiceSettings) GetSettings() *MeshConfig_ServiceSettings_Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *MeshConfig_ServiceSettings) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

// Settings for the selected services.
type MeshConfig_ServiceSettings_Settings struct {
	// If true, specifies that the client and service endpoints must reside in the same cluster.
	// By default, in multi-cluster deployments, the Istio control plane assumes all service
	// endpoints to be reachable from any client in any of the clusters which are part of the
	// mesh. This configuration option limits the set of service endpoints visible to a client
	// to be cluster scoped.
	//
	// There are some common scenarios when this can be useful:
	//
	//   - A service (or group of services) is inherently local to the cluster and has local storage
	//     for that cluster. For example, the kube-system namespace (e.g. the Kube API Server).
	//   - A mesh administrator wants to slowly migrate services to Istio. They might start by first
	//     having services cluster-local and then slowly transition them to mesh-wide. They could do
	//     this service-by-service (e.g. mysvc.myns.svc.cluster.local) or as a group
	//     (e.g. *.myns.svc.cluster.local).
	//
	// By default, Istio will consider all services in the kube-system namespace to be cluster-local,
	// unless explicitly overridden here.
	ClusterLocal         bool     `protobuf:"varint,1,opt,name=cluster_local,json=clusterLocal,proto3" json:"clusterLocal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshConfig_ServiceSettings_Settings) Reset()         { *m = MeshConfig_ServiceSettings_Settings{} }
func (m *MeshConfig_ServiceSettings_Settings) String() string { return proto.CompactTextString(m) }
func (*MeshConfig_ServiceSettings_Settings) ProtoMessage()    {}
func (*MeshConfig_ServiceSettings_Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 3, 0}
}

func (m *MeshConfig_ServiceSettings_Settings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_ServiceSettings_Settings.Unmarshal(m, b)
}
func (m *MeshConfig_ServiceSettings_Settings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_ServiceSettings_Settings.Marshal(b, m, deterministic)
}
func (m *MeshConfig_ServiceSettings_Settings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_ServiceSettings_Settings.Merge(m, src)
}
func (m *MeshConfig_ServiceSettings_Settings) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_ServiceSettings_Settings.Size(m)
}
func (m *MeshConfig_ServiceSettings_Settings) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_ServiceSettings_Settings.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_ServiceSettings_Settings proto.InternalMessageInfo

func (m *MeshConfig_ServiceSettings_Settings) GetClusterLocal() bool {
	if m != nil {
		return m.ClusterLocal
	}
	return false
}

type MeshConfig_CA struct {
	// REQUIRED. Address of the CA server implementing the Istio CA gRPC API.
	// Can be IP address or a fully qualified DNS name with port
	// Eg: custom-ca.default.svc.cluster.local:8932, 192.168.23.2:9000
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Use the tls_settings to specify the tls mode to use.
	// Regarding tls_settings:
	// - DISABLE MODE is legitimate for the case Istiod is making the request via an Envoy sidecar.
	// DISABLE MODE can also be used for testing
	// - TLS MUTUAL MODE be on by default. If the CA certificates
	// (cert bundle to verify the CA server's certificate) is omitted, Istiod will
	// use the system root certs to verify the CA server's certificate.
	TlsSettings *v1alpha3.ClientTLSSettings `protobuf:"bytes,2,opt,name=tls_settings,json=tlsSettings,proto3" json:"tlsSettings,omitempty"`
	// timeout for forward CSR requests from Istiod to External CA
	// Default: 10s
	RequestTimeout *duration.Duration `protobuf:"bytes,3,opt,name=request_timeout,json=requestTimeout,proto3" json:"requestTimeout,omitempty"`
	// Use istiod_side to specify CA Server integrate to Istiod side or Agent side
	// Default: true
	IstiodSide           bool     `protobuf:"varint,4,opt,name=istiod_side,json=istiodSide,proto3" json:"istiodSide,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshConfig_CA) Reset()         { *m = MeshConfig_CA{} }
func (m *MeshConfig_CA) String() string { return proto.CompactTextString(m) }
func (*MeshConfig_CA) ProtoMessage()    {}
func (*MeshConfig_CA) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 4}
}

func (m *MeshConfig_CA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_CA.Unmarshal(m, b)
}
func (m *MeshConfig_CA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_CA.Marshal(b, m, deterministic)
}
func (m *MeshConfig_CA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_CA.Merge(m, src)
}
func (m *MeshConfig_CA) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_CA.Size(m)
}
func (m *MeshConfig_CA) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_CA.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_CA proto.InternalMessageInfo

func (m *MeshConfig_CA) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MeshConfig_CA) GetTlsSettings() *v1alpha3.ClientTLSSettings {
	if m != nil {
		return m.TlsSettings
	}
	return nil
}

func (m *MeshConfig_CA) GetRequestTimeout() *duration.Duration {
	if m != nil {
		return m.RequestTimeout
	}
	return nil
}

func (m *MeshConfig_CA) GetIstiodSide() bool {
	if m != nil {
		return m.IstiodSide
	}
	return false
}

type MeshConfig_ExtensionProvider struct {
	// REQUIRED. A unique name identifying the extension provider.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// REQUIRED. Specifies detailed configuration for the extension provider.
	//
	// Types that are valid to be assigned to Provider:
	//	*MeshConfig_ExtensionProvider_EnvoyExtAuthzHttp
	//	*MeshConfig_ExtensionProvider_EnvoyExtAuthzGrpc
	Provider             isMeshConfig_ExtensionProvider_Provider `protobuf_oneof:"provider"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *MeshConfig_ExtensionProvider) Reset()         { *m = MeshConfig_ExtensionProvider{} }
func (m *MeshConfig_ExtensionProvider) String() string { return proto.CompactTextString(m) }
func (*MeshConfig_ExtensionProvider) ProtoMessage()    {}
func (*MeshConfig_ExtensionProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 5}
}

func (m *MeshConfig_ExtensionProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_ExtensionProvider.Unmarshal(m, b)
}
func (m *MeshConfig_ExtensionProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_ExtensionProvider.Marshal(b, m, deterministic)
}
func (m *MeshConfig_ExtensionProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_ExtensionProvider.Merge(m, src)
}
func (m *MeshConfig_ExtensionProvider) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_ExtensionProvider.Size(m)
}
func (m *MeshConfig_ExtensionProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_ExtensionProvider.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_ExtensionProvider proto.InternalMessageInfo

func (m *MeshConfig_ExtensionProvider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isMeshConfig_ExtensionProvider_Provider interface {
	isMeshConfig_ExtensionProvider_Provider()
}

type MeshConfig_ExtensionProvider_EnvoyExtAuthzHttp struct {
	EnvoyExtAuthzHttp *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider `protobuf:"bytes,2,opt,name=envoy_ext_authz_http,json=envoyExtAuthzHttp,proto3,oneof"`
}

type MeshConfig_ExtensionProvider_EnvoyExtAuthzGrpc struct {
	EnvoyExtAuthzGrpc *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider `protobuf:"bytes,3,opt,name=envoy_ext_authz_grpc,json=envoyExtAuthzGrpc,proto3,oneof"`
}

func (*MeshConfig_ExtensionProvider_EnvoyExtAuthzHttp) isMeshConfig_ExtensionProvider_Provider() {}

func (*MeshConfig_ExtensionProvider_EnvoyExtAuthzGrpc) isMeshConfig_ExtensionProvider_Provider() {}

func (m *MeshConfig_ExtensionProvider) GetProvider() isMeshConfig_ExtensionProvider_Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *MeshConfig_ExtensionProvider) GetEnvoyExtAuthzHttp() *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider {
	if x, ok := m.GetProvider().(*MeshConfig_ExtensionProvider_EnvoyExtAuthzHttp); ok {
		return x.EnvoyExtAuthzHttp
	}
	return nil
}

func (m *MeshConfig_ExtensionProvider) GetEnvoyExtAuthzGrpc() *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider {
	if x, ok := m.GetProvider().(*MeshConfig_ExtensionProvider_EnvoyExtAuthzGrpc); ok {
		return x.EnvoyExtAuthzGrpc
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MeshConfig_ExtensionProvider) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MeshConfig_ExtensionProvider_EnvoyExtAuthzHttp)(nil),
		(*MeshConfig_ExtensionProvider_EnvoyExtAuthzGrpc)(nil),
	}
}

type MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider struct {
	// REQUIRED. Specifies the service that implements the Envoy ext_authz HTTP authorization service.
	// The format is "[<Namespace>/]<Hostname>". The specification of <Namespace> is required only when it is insufficient
	// to unambiguously resolve a service in the service registry. The <Hostname> is a fully qualified host name of a
	// service defined by the Kubernetes service or ServiceEntry.
	//
	// Example: "my-ext-authz.foo.svc.cluster.local" or "bar/my-ext-authz.example.com".
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// REQUIRED. Specifies the port of the service.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Sets a prefix to the value of authorization request header *Path*.
	// For example, setting this to "/check" for an original user request at path "/admin" will cause the
	// authorization check request to be sent to the authorization service at the path "/check/admin" instead of "/admin".
	PathPrefix string `protobuf:"bytes,3,opt,name=path_prefix,json=pathPrefix,proto3" json:"pathPrefix,omitempty"`
	// If true, the user request will be allowed even if the communication with the authorization service has failed,
	// or if the authorization service has returned a HTTP 5xx error.
	// Default is false and the request will be rejected with "Forbidden" response.
	FailOpen bool `protobuf:"varint,4,opt,name=fail_open,json=failOpen,proto3" json:"failOpen,omitempty"`
	// Sets the HTTP status that is returned to the client when there is a network error to the authorization service.
	// The default status is "403" (HTTP Forbidden).
	StatusOnError string `protobuf:"bytes,5,opt,name=status_on_error,json=statusOnError,proto3" json:"statusOnError,omitempty"`
	// List of headers that should be included in the authorization request sent to the authorization service.
	// Note that in addition to the headers supplied by users:
	// 1. *Host*, *Method*, *Path* and *Content-Length* are automatically sent.
	// 2. *Content-Length* will be set to 0 and the request will not have a message body.
	IncludeHeadersInCheck []string `protobuf:"bytes,6,rep,name=include_headers_in_check,json=includeHeadersInCheck,proto3" json:"includeHeadersInCheck,omitempty"`
	// List of headers from the authorization service that should be added or overridden in the original request and
	// forwarded to the upstream when the authorization check result is allowed (HTTP code 200).
	// If not specified, the original request will not be modified and forwarded to backend as-is.
	// Note, any existing headers will be overridden.
	HeadersToUpstreamOnAllow []string `protobuf:"bytes,7,rep,name=headers_to_upstream_on_allow,json=headersToUpstreamOnAllow,proto3" json:"headersToUpstreamOnAllow,omitempty"`
	// List of headers from the authorization service that should be forwarded to downstream when the authorization
	// check result is not allowed (HTTP code other than 200).
	// If not specified, all the authorization response headers, except *Authority (Host)* will be in the response to
	// the downstream.
	// When a header is included in this list, *Path*, *Status*, *Content-Length*, *WWWAuthenticate* and *Location* are
	// automatically added.
	// Note, the body from the authorization service is always included in the response to downstream.
	HeadersToDownstreamOnDeny []string `protobuf:"bytes,8,rep,name=headers_to_downstream_on_deny,json=headersToDownstreamOnDeny,proto3" json:"headersToDownstreamOnDeny,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) Reset() {
	*m = MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider{}
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) String() string {
	return proto.CompactTextString(m)
}
func (*MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) ProtoMessage() {}
func (*MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 5, 0}
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider.Unmarshal(m, b)
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider.Marshal(b, m, deterministic)
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider.Merge(m, src)
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider.Size(m)
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider proto.InternalMessageInfo

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) GetPathPrefix() string {
	if m != nil {
		return m.PathPrefix
	}
	return ""
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) GetFailOpen() bool {
	if m != nil {
		return m.FailOpen
	}
	return false
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) GetStatusOnError() string {
	if m != nil {
		return m.StatusOnError
	}
	return ""
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) GetIncludeHeadersInCheck() []string {
	if m != nil {
		return m.IncludeHeadersInCheck
	}
	return nil
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) GetHeadersToUpstreamOnAllow() []string {
	if m != nil {
		return m.HeadersToUpstreamOnAllow
	}
	return nil
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider) GetHeadersToDownstreamOnDeny() []string {
	if m != nil {
		return m.HeadersToDownstreamOnDeny
	}
	return nil
}

type MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider struct {
	// REQUIRED. Specifies the service that implements the Envoy ext_authz gRPC authorization service.
	// The format is "[<Namespace>/]<Hostname>". The specification of <Namespace> is required only when it is insufficient
	// to unambiguously resolve a service in the service registry. The <Hostname> is a fully qualified host name of a
	// service defined by the Kubernetes service or ServiceEntry.
	//
	// Example: "my-ext-authz.foo.svc.cluster.local" or "bar/my-ext-authz.example.com".
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// REQUIRED. Specifies the port of the service.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// If true, the user request will be allowed even if the communication with the authorization service has failed,
	// or if the authorization service has returned a HTTP 5xx error.
	// Default is false and the request will be rejected with "Forbidden" response.
	FailOpen bool `protobuf:"varint,3,opt,name=fail_open,json=failOpen,proto3" json:"failOpen,omitempty"`
	// Sets the HTTP status that is returned to the client when there is a network error to the authorization service.
	// The default status is "403" (HTTP Forbidden).
	StatusOnError        string   `protobuf:"bytes,4,opt,name=status_on_error,json=statusOnError,proto3" json:"statusOnError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) Reset() {
	*m = MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider{}
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) String() string {
	return proto.CompactTextString(m)
}
func (*MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) ProtoMessage() {}
func (*MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{0, 5, 1}
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider.Unmarshal(m, b)
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider.Marshal(b, m, deterministic)
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider.Merge(m, src)
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) XXX_Size() int {
	return xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider.Size(m)
}
func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider proto.InternalMessageInfo

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) GetFailOpen() bool {
	if m != nil {
		return m.FailOpen
	}
	return false
}

func (m *MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider) GetStatusOnError() string {
	if m != nil {
		return m.StatusOnError
	}
	return ""
}

// ConfigSource describes information about a configuration store inside a
// mesh. A single control plane instance can interact with one or more data
// sources.
type ConfigSource struct {
	// Address of the server implementing the Istio Mesh Configuration
	// protocol (MCP). Can be IP address or a fully qualified DNS name.
	// Use fs:/// to specify a file-based backend with absolute path to the directory.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Use the tls_settings to specify the tls mode to use. If the MCP server
	// uses Istio mutual TLS and shares the root CA with Pilot, specify the TLS
	// mode as `ISTIO_MUTUAL`.
	TlsSettings *v1alpha3.ClientTLSSettings `protobuf:"bytes,2,opt,name=tls_settings,json=tlsSettings,proto3" json:"tlsSettings,omitempty"`
	// Describes the source of configuration, if nothing is specified default is MCP
	SubscribedResources  []Resource `protobuf:"varint,3,rep,packed,name=subscribed_resources,json=subscribedResources,proto3,enum=istio.mesh.v1alpha1.Resource" json:"subscribedResources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigSource) Reset()         { *m = ConfigSource{} }
func (m *ConfigSource) String() string { return proto.CompactTextString(m) }
func (*ConfigSource) ProtoMessage()    {}
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{1}
}

func (m *ConfigSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSource.Unmarshal(m, b)
}
func (m *ConfigSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSource.Marshal(b, m, deterministic)
}
func (m *ConfigSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSource.Merge(m, src)
}
func (m *ConfigSource) XXX_Size() int {
	return xxx_messageInfo_ConfigSource.Size(m)
}
func (m *ConfigSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSource.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSource proto.InternalMessageInfo

func (m *ConfigSource) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ConfigSource) GetTlsSettings() *v1alpha3.ClientTLSSettings {
	if m != nil {
		return m.TlsSettings
	}
	return nil
}

func (m *ConfigSource) GetSubscribedResources() []Resource {
	if m != nil {
		return m.SubscribedResources
	}
	return nil
}

// Certificate configures the provision of a certificate and its key.
// Example 1: key and cert stored in a secret
// ```
// { secretName: galley-cert
//   secretNamespace: istio-system
//   dnsNames:
//     - galley.istio-system.svc
//     - galley.mydomain.com
// }
// ```
// Example 2: key and cert stored in a directory
// ```
// { dnsNames:
//     - pilot.istio-system
//     - pilot.istio-system.svc
//     - pilot.mydomain.com
// }
// ```
type Certificate struct {
	// Name of the secret the certificate and its key will be stored into.
	// If it is empty, it will not be stored into a secret.
	// Instead, the certificate and its key will be stored into a hard-coded directory.
	SecretName string `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secretName,omitempty"`
	// The DNS names for the certificate. A certificate may contain
	// multiple DNS names.
	DnsNames             []string `protobuf:"bytes,2,rep,name=dns_names,json=dnsNames,proto3" json:"dnsNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c7ece76d5d5022, []int{2}
}

func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *Certificate) GetDnsNames() []string {
	if m != nil {
		return m.DnsNames
	}
	return nil
}

func init() {
	proto.RegisterEnum("istio.mesh.v1alpha1.Resource", Resource_name, Resource_value)
	proto.RegisterEnum("istio.mesh.v1alpha1.MeshConfig_IngressControllerMode", MeshConfig_IngressControllerMode_name, MeshConfig_IngressControllerMode_value)
	proto.RegisterEnum("istio.mesh.v1alpha1.MeshConfig_AuthPolicy", MeshConfig_AuthPolicy_name, MeshConfig_AuthPolicy_value)
	proto.RegisterEnum("istio.mesh.v1alpha1.MeshConfig_AccessLogEncoding", MeshConfig_AccessLogEncoding_name, MeshConfig_AccessLogEncoding_value)
	proto.RegisterEnum("istio.mesh.v1alpha1.MeshConfig_H2UpgradePolicy", MeshConfig_H2UpgradePolicy_name, MeshConfig_H2UpgradePolicy_value)
	proto.RegisterEnum("istio.mesh.v1alpha1.MeshConfig_OutboundTrafficPolicy_Mode", MeshConfig_OutboundTrafficPolicy_Mode_name, MeshConfig_OutboundTrafficPolicy_Mode_value)
	proto.RegisterType((*MeshConfig)(nil), "istio.mesh.v1alpha1.MeshConfig")
	proto.RegisterType((*MeshConfig_OutboundTrafficPolicy)(nil), "istio.mesh.v1alpha1.MeshConfig.OutboundTrafficPolicy")
	proto.RegisterType((*MeshConfig_CertificateData)(nil), "istio.mesh.v1alpha1.MeshConfig.CertificateData")
	proto.RegisterType((*MeshConfig_ThriftConfig)(nil), "istio.mesh.v1alpha1.MeshConfig.ThriftConfig")
	proto.RegisterType((*MeshConfig_ServiceSettings)(nil), "istio.mesh.v1alpha1.MeshConfig.ServiceSettings")
	proto.RegisterType((*MeshConfig_ServiceSettings_Settings)(nil), "istio.mesh.v1alpha1.MeshConfig.ServiceSettings.Settings")
	proto.RegisterType((*MeshConfig_CA)(nil), "istio.mesh.v1alpha1.MeshConfig.CA")
	proto.RegisterType((*MeshConfig_ExtensionProvider)(nil), "istio.mesh.v1alpha1.MeshConfig.ExtensionProvider")
	proto.RegisterType((*MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationHttpProvider)(nil), "istio.mesh.v1alpha1.MeshConfig.ExtensionProvider.EnvoyExternalAuthorizationHttpProvider")
	proto.RegisterType((*MeshConfig_ExtensionProvider_EnvoyExternalAuthorizationGrpcProvider)(nil), "istio.mesh.v1alpha1.MeshConfig.ExtensionProvider.EnvoyExternalAuthorizationGrpcProvider")
	proto.RegisterType((*ConfigSource)(nil), "istio.mesh.v1alpha1.ConfigSource")
	proto.RegisterType((*Certificate)(nil), "istio.mesh.v1alpha1.Certificate")
}

func init() {
	proto.RegisterFile("mesh/v1alpha1/config.proto", fileDescriptor_b5c7ece76d5d5022)
}

var fileDescriptor_b5c7ece76d5d5022 = []byte{
	// 2442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xdb, 0x72, 0x1b, 0xb7,
	0x19, 0x36, 0xa5, 0x8d, 0xbd, 0x82, 0x44, 0x71, 0x05, 0x49, 0xf6, 0x9a, 0x3e, 0xc9, 0x4a, 0x6c,
	0x2b, 0x6e, 0x4a, 0x46, 0x72, 0x0e, 0x4e, 0x32, 0xd3, 0x29, 0x45, 0xd2, 0x96, 0x18, 0x5a, 0x54,
	0x21, 0xca, 0x39, 0x5d, 0x60, 0xa0, 0x5d, 0x90, 0xdc, 0x6a, 0xb9, 0xd8, 0x02, 0x58, 0x59, 0xca,
	0x4c, 0x9f, 0xa0, 0x8f, 0xd0, 0x67, 0x68, 0x1f, 0xa0, 0xaf, 0xd0, 0xdb, 0xbe, 0x43, 0x1f, 0xa1,
	0xb7, 0x1d, 0x1c, 0x96, 0xa4, 0x24, 0x36, 0x4c, 0x3a, 0x9d, 0xde, 0x71, 0x3f, 0xfc, 0xff, 0x07,
	0xe0, 0xc7, 0x7f, 0x24, 0x28, 0x0f, 0xa9, 0x18, 0x54, 0xcf, 0xb6, 0x49, 0x9c, 0x0e, 0xc8, 0x76,
	0x35, 0x60, 0x49, 0x2f, 0xea, 0x57, 0x52, 0xce, 0x24, 0x83, 0xab, 0x91, 0x90, 0x11, 0xab, 0x28,
	0x89, 0x4a, 0x2e, 0x51, 0x7e, 0xd8, 0x67, 0xac, 0x1f, 0xd3, 0xaa, 0x16, 0x39, 0xc9, 0x7a, 0xd5,
	0x30, 0xe3, 0x44, 0x46, 0x2c, 0x31, 0x4a, 0xd7, 0xd7, 0xdf, 0x71, 0x92, 0xa6, 0x94, 0x0b, 0xbb,
	0x7e, 0xf7, 0xf2, 0x86, 0x29, 0x67, 0xe7, 0x17, 0x76, 0xe9, 0x79, 0x42, 0xe5, 0x3b, 0xc6, 0x4f,
	0xa3, 0xa4, 0x9f, 0x0b, 0xbc, 0xa8, 0x86, 0x54, 0xc8, 0x28, 0xd1, 0x3b, 0x60, 0x9e, 0xc5, 0xd4,
	0xca, 0x7e, 0x72, 0xfa, 0x52, 0x54, 0x22, 0x56, 0x25, 0x69, 0x34, 0x24, 0xc1, 0x20, 0x4a, 0x28,
	0xbf, 0xa8, 0xa6, 0xa7, 0x7d, 0x05, 0x88, 0xea, 0x90, 0x4a, 0x52, 0x3d, 0xdb, 0xae, 0xf6, 0x69,
	0x42, 0x39, 0x91, 0x34, 0x34, 0x5a, 0x9b, 0x7f, 0xdb, 0x02, 0xe0, 0x0d, 0x15, 0x83, 0xba, 0xbe,
	0x26, 0x7c, 0x0e, 0x56, 0xf4, 0xfe, 0x38, 0x8e, 0x84, 0xa4, 0x09, 0x4e, 0x19, 0x97, 0xbe, 0xb3,
	0x51, 0xd8, 0x7a, 0x0f, 0x95, 0xf4, 0x42, 0x5b, 0xe3, 0x87, 0x8c, 0x4b, 0xf8, 0x14, 0x18, 0x08,
	0x0f, 0xa4, 0x4c, 0x8d, 0xe4, 0x7b, 0x5a, 0xb2, 0xa8, 0xe1, 0x3d, 0x29, 0x53, 0x2d, 0xb7, 0x0b,
	0x4a, 0x01, 0x4b, 0x12, 0x1a, 0x48, 0x2c, 0xa3, 0x21, 0x65, 0x99, 0xf4, 0x6f, 0x6e, 0x14, 0xb6,
	0x16, 0x77, 0xee, 0x56, 0x8c, 0x65, 0x2a, 0xb9, 0x65, 0x2a, 0x0d, 0x6b, 0x39, 0xb4, 0x6c, 0x35,
	0xba, 0x46, 0x01, 0x7e, 0x03, 0xca, 0x5a, 0x28, 0x60, 0x31, 0x0e, 0xa9, 0xa4, 0x81, 0xbe, 0x7d,
	0x4e, 0xf7, 0x7c, 0x16, 0x9d, 0x9f, 0x2b, 0x37, 0x72, 0xdd, 0x9c, 0x98, 0x81, 0xa2, 0x0c, 0x52,
	0x7c, 0x4a, 0x69, 0x4a, 0xe2, 0xe8, 0x8c, 0xfa, 0xf7, 0x35, 0x57, 0xab, 0x62, 0x5e, 0x7a, 0x6c,
	0xff, 0xfc, 0xbd, 0x5f, 0x54, 0xea, 0xe6, 0x68, 0x11, 0x4b, 0x0e, 0x19, 0x8b, 0x8f, 0xa8, 0x94,
	0x51, 0xd2, 0x17, 0x95, 0x6e, 0xfd, 0x70, 0xfc, 0x3b, 0x48, 0xbf, 0xce, 0x19, 0xd1, 0x92, 0x9c,
	0xf8, 0x82, 0xef, 0x83, 0x62, 0x94, 0xf4, 0x39, 0x15, 0x02, 0x07, 0x31, 0x11, 0xc2, 0xbf, 0xb5,
	0x51, 0xd8, 0x5a, 0x40, 0x4b, 0x16, 0xac, 0x2b, 0x0c, 0x3e, 0x03, 0xa5, 0x5c, 0x48, 0x50, 0x7e,
	0x16, 0x05, 0xd4, 0x77, 0xb5, 0xd8, 0xb2, 0x85, 0x8f, 0x0c, 0x0a, 0x87, 0xe0, 0xce, 0x88, 0x8d,
	0x25, 0x92, 0xb3, 0x38, 0xa6, 0x1c, 0x0f, 0x59, 0x48, 0xfd, 0x85, 0x8d, 0xc2, 0xd6, 0xf2, 0xce,
	0xa7, 0x95, 0x29, 0x2e, 0x5b, 0x19, 0xbf, 0x78, 0x65, 0xdf, 0xee, 0x3b, 0xd2, 0x7e, 0xc3, 0x42,
	0x8a, 0xd6, 0xa3, 0x69, 0x30, 0xfc, 0x10, 0x78, 0xe3, 0x73, 0xc5, 0x34, 0x90, 0x8c, 0xfb, 0x9f,
	0xe8, 0x83, 0x95, 0x46, 0x07, 0x33, 0x30, 0x7c, 0x02, 0x96, 0x69, 0x42, 0x4e, 0x62, 0x8a, 0x25,
	0x27, 0x41, 0x94, 0xf4, 0xfd, 0xa5, 0x8d, 0xc2, 0x96, 0x8b, 0x8a, 0x06, 0xed, 0x1a, 0x50, 0x39,
	0x11, 0x09, 0x02, 0x45, 0x18, 0xb3, 0x3e, 0xee, 0x45, 0x31, 0xf5, 0x8b, 0x9a, 0xb0, 0x68, 0xe0,
	0x36, 0xeb, 0xbf, 0x8a, 0x62, 0xaa, 0x1c, 0x73, 0x52, 0x8e, 0xf1, 0x21, 0x91, 0xbe, 0x6f, 0xb6,
	0x1e, 0x4b, 0x6a, 0x18, 0x12, 0xb0, 0x3a, 0x21, 0x4b, 0x93, 0x80, 0x85, 0x6a, 0xff, 0x7b, 0xda,
	0x20, 0xdb, 0xb3, 0x0c, 0x52, 0xcb, 0xd9, 0x9a, 0x56, 0x11, 0xad, 0x90, 0xab, 0x10, 0x6c, 0x80,
	0x47, 0xf6, 0x76, 0x34, 0x39, 0x63, 0x17, 0x78, 0x62, 0xbf, 0xfc, 0xc1, 0xb6, 0xf4, 0x75, 0xef,
	0x19, 0xb1, 0xa6, 0x92, 0x1a, 0x31, 0xe7, 0xaf, 0xf7, 0x15, 0x28, 0x87, 0x91, 0x98, 0xa0, 0x31,
	0x51, 0x47, 0xb9, 0x22, 0xf2, 0x5f, 0x6a, 0x82, 0x3b, 0x56, 0x42, 0x33, 0xb4, 0xed, 0x7a, 0x9b,
	0xf5, 0xe1, 0x6b, 0xb0, 0x1c, 0xd2, 0x1e, 0xc9, 0x62, 0x89, 0x4d, 0x8e, 0xf2, 0x97, 0xb5, 0xeb,
	0x6e, 0x4c, 0xbd, 0xe0, 0xa1, 0x0a, 0x49, 0x73, 0x43, 0x54, 0xb4, 0x7a, 0x36, 0xe6, 0x87, 0xe0,
	0x0e, 0xcb, 0xe4, 0x09, 0xcb, 0x92, 0x50, 0xbd, 0x55, 0xaf, 0x17, 0x05, 0x38, 0x65, 0x71, 0x14,
	0x5c, 0xf8, 0x2b, 0x9a, 0x71, 0xa6, 0x0f, 0x75, 0xac, 0x7a, 0xd7, 0x68, 0x1f, 0x6a, 0x65, 0xb4,
	0xce, 0xa6, 0xc1, 0x70, 0x0f, 0x2c, 0x9b, 0xf3, 0x62, 0xc1, 0x32, 0x1e, 0x50, 0xe1, 0xdf, 0xde,
	0x98, 0xdf, 0x5a, 0xdc, 0x79, 0x3c, 0x75, 0x17, 0xb3, 0xc3, 0x91, 0x96, 0x44, 0xc5, 0x60, 0xe2,
	0x4b, 0xc0, 0x06, 0xf0, 0xec, 0x23, 0x90, 0x4c, 0x32, 0x3c, 0x94, 0xb1, 0xf0, 0x7f, 0xa5, 0x4f,
	0x5c, 0xbe, 0x96, 0x0a, 0x76, 0x19, 0x8b, 0xdf, 0x92, 0x38, 0xa3, 0xc8, 0xba, 0x65, 0x2d, 0x93,
	0xec, 0x8d, 0x8c, 0x05, 0x7c, 0x0c, 0x96, 0x24, 0xcf, 0x84, 0xc4, 0x21, 0x1b, 0x92, 0x28, 0xf1,
	0xcb, 0xda, 0xa9, 0x16, 0x35, 0xd6, 0xd0, 0x10, 0xfc, 0x18, 0xac, 0x4d, 0x8a, 0x60, 0x12, 0x47,
	0x44, 0x50, 0xe1, 0x57, 0x36, 0xe6, 0xb7, 0x16, 0x10, 0x9c, 0x10, 0xad, 0x99, 0x15, 0xf8, 0x2d,
	0x28, 0x05, 0x04, 0x07, 0x94, 0xcb, 0xa8, 0x17, 0x05, 0x44, 0x52, 0xe1, 0x7f, 0xa9, 0x6f, 0x59,
	0x9d, 0x65, 0xcb, 0xfa, 0x58, 0xa7, 0x41, 0x24, 0x41, 0xcb, 0x01, 0x99, 0x80, 0x04, 0xfc, 0x02,
	0xdc, 0xcd, 0x9f, 0xdd, 0x7a, 0x1a, 0xa6, 0xe7, 0x2a, 0xf9, 0x62, 0xc9, 0xfc, 0x47, 0xfa, 0x40,
	0xb7, 0xad, 0x80, 0x75, 0xb3, 0xa6, 0x5e, 0xee, 0x32, 0xb8, 0x07, 0x1e, 0xe7, 0xaa, 0x67, 0x11,
	0x97, 0x19, 0x89, 0xa7, 0x50, 0x6c, 0x68, 0x8a, 0x07, 0x56, 0xf0, 0xad, 0x91, 0xbb, 0xca, 0xd4,
	0x02, 0x9b, 0x39, 0xd3, 0xd5, 0x6a, 0x34, 0x41, 0xf5, 0x58, 0x53, 0x3d, 0xb4, 0x92, 0x8d, 0xb1,
	0x20, 0xca, 0xe2, 0x31, 0xd7, 0x13, 0xb0, 0xcc, 0x19, 0x93, 0x38, 0x21, 0x43, 0x2a, 0x52, 0x12,
	0x50, 0x7f, 0xd3, 0x24, 0x00, 0x85, 0x1e, 0xe4, 0x20, 0xec, 0x81, 0xd5, 0x98, 0x05, 0x24, 0x8e,
	0xe4, 0x05, 0x8e, 0x4f, 0xb0, 0x30, 0xa9, 0xd6, 0x7f, 0x5f, 0xbf, 0xf7, 0x67, 0x3f, 0x91, 0xae,
	0xdb, 0x56, 0xab, 0xcd, 0x48, 0xb8, 0x4b, 0x62, 0x92, 0x04, 0x94, 0xdb, 0x44, 0x8d, 0x56, 0x72,
	0xca, 0xf6, 0x89, 0x85, 0x60, 0x1d, 0x78, 0x61, 0x22, 0x30, 0xa7, 0x3d, 0x4e, 0xc5, 0x00, 0xab,
	0x5a, 0xe9, 0x7f, 0x30, 0xb3, 0x5c, 0x85, 0x89, 0x40, 0x46, 0x03, 0x11, 0x49, 0xe1, 0x0f, 0x60,
	0x65, 0xb0, 0x83, 0xb3, 0xb4, 0xcf, 0x49, 0x48, 0xf3, 0x60, 0xfa, 0x50, 0xe7, 0x9f, 0x99, 0x0e,
	0xb0, 0xb7, 0x73, 0x6c, 0xf4, 0x6c, 0x18, 0x95, 0x06, 0x97, 0x01, 0xe5, 0x01, 0x51, 0x62, 0xc2,
	0x35, 0x88, 0x33, 0x21, 0x29, 0xc7, 0x42, 0x12, 0x63, 0x40, 0xff, 0x23, 0x6d, 0xbb, 0xdb, 0x56,
	0xa0, 0x6e, 0xd6, 0x8f, 0x24, 0xd1, 0x96, 0x54, 0x09, 0x67, 0x14, 0xea, 0xd7, 0x75, 0x7f, 0xad,
	0x75, 0x47, 0xc9, 0xe0, 0xaa, 0x72, 0x03, 0x2c, 0x5d, 0x72, 0xe8, 0xaa, 0x76, 0xe8, 0xe9, 0xe9,
	0x66, 0xc2, 0x65, 0xd1, 0x25, 0x2d, 0xf8, 0x3b, 0x50, 0x94, 0x03, 0x1e, 0xf5, 0x46, 0x59, 0x6b,
	0x5b, 0x1b, 0xf7, 0xa3, 0x59, 0x66, 0xe9, 0x6a, 0x25, 0x9b, 0xc1, 0x96, 0xe4, 0xc4, 0x17, 0xfc,
	0x1e, 0x78, 0xb9, 0x1f, 0x5b, 0xb7, 0x10, 0xfe, 0xce, 0xcf, 0x8b, 0x36, 0xeb, 0xd8, 0x79, 0xe1,
	0x46, 0x25, 0x71, 0x19, 0x80, 0x08, 0xdc, 0xb1, 0x39, 0x26, 0xe5, 0x6c, 0x48, 0xe5, 0x80, 0x66,
	0x02, 0x0f, 0x29, 0xef, 0x53, 0xff, 0xc5, 0xcc, 0x54, 0xb3, 0x6e, 0x54, 0x0f, 0x47, 0x9a, 0x6f,
	0x94, 0x22, 0xfc, 0x01, 0xdc, 0x3f, 0xa3, 0x3c, 0xea, 0x5d, 0x4c, 0x26, 0x08, 0x4c, 0x24, 0x0e,
	0xe2, 0x88, 0x26, 0xd2, 0xff, 0x6c, 0x26, 0xf1, 0x5d, 0xa3, 0x3f, 0x61, 0xe5, 0x9a, 0xac, 0x6b,
	0x65, 0xb8, 0x03, 0xe6, 0x02, 0xe2, 0x7f, 0xae, 0x29, 0x36, 0x67, 0x26, 0x9b, 0x1a, 0x9a, 0x0b,
	0x08, 0x3c, 0x01, 0xab, 0xf4, 0x5c, 0xd2, 0x44, 0xa8, 0x20, 0x4e, 0x39, 0x3b, 0x8b, 0x42, 0xca,
	0x85, 0xff, 0x85, 0xb6, 0xe1, 0xcc, 0x82, 0xd9, 0xcc, 0x55, 0x0f, 0xad, 0x26, 0x82, 0xf4, 0x2a,
	0x24, 0x60, 0x08, 0x56, 0xc3, 0x48, 0x04, 0xec, 0x8c, 0xf2, 0x8b, 0x51, 0xf3, 0x20, 0xfc, 0xaf,
	0xf4, 0x1e, 0x2f, 0x2a, 0xa6, 0x79, 0xad, 0x4c, 0x36, 0xaf, 0x95, 0xf4, 0xb4, 0xaf, 0x00, 0x51,
	0x51, 0xcd, 0x6b, 0xe5, 0x6c, 0xbb, 0xd2, 0x26, 0x27, 0x34, 0xce, 0x3b, 0x0c, 0x04, 0x47, 0x7c,
	0x39, 0x24, 0xca, 0x7f, 0x29, 0x80, 0xf5, 0xa9, 0xd5, 0x08, 0x1e, 0x00, 0x47, 0xb7, 0x45, 0x05,
	0x1d, 0x85, 0x5f, 0xfe, 0x57, 0x25, 0xad, 0xa2, 0x7b, 0x23, 0xcd, 0xb3, 0xd9, 0x00, 0x8e, 0x6e,
	0x89, 0x56, 0x40, 0x11, 0x35, 0x5f, 0xef, 0x1f, 0x75, 0xd1, 0x77, 0xb8, 0x73, 0xd0, 0xfe, 0xce,
	0xbb, 0x01, 0x8b, 0x60, 0xa1, 0xd6, 0x6e, 0x77, 0xbe, 0xc1, 0xb5, 0x83, 0xef, 0xbc, 0xc2, 0xa6,
	0xe3, 0xce, 0x79, 0x73, 0xcf, 0xd7, 0xde, 0xee, 0xa3, 0xee, 0x71, 0xad, 0x8d, 0x8f, 0x9a, 0xe8,
	0xed, 0x7e, 0xbd, 0xa9, 0x85, 0xcb, 0x7d, 0x50, 0xba, 0x92, 0xf0, 0x21, 0x04, 0xf3, 0x29, 0x1d,
	0xea, 0x73, 0x2e, 0xec, 0xdd, 0x40, 0xea, 0x03, 0x7e, 0x04, 0x56, 0x44, 0x1a, 0xf5, 0x7a, 0x14,
	0x9f, 0x64, 0x49, 0x18, 0x53, 0x9c, 0xf1, 0xd8, 0x9f, 0xb3, 0x12, 0x25, 0xb3, 0xb4, 0xab, 0x57,
	0x8e, 0x79, 0xbc, 0x0b, 0x81, 0x37, 0xe9, 0x58, 0x21, 0x91, 0xa4, 0xfc, 0x47, 0xb0, 0x34, 0x19,
	0x41, 0xf0, 0x03, 0xb0, 0xac, 0x52, 0x1b, 0x8e, 0xa3, 0x61, 0x24, 0x35, 0x5d, 0xc1, 0xf4, 0xa1,
	0x0a, 0x6d, 0x2b, 0xf0, 0x98, 0xc7, 0xf0, 0x35, 0x80, 0x13, 0x52, 0x79, 0xbb, 0x3d, 0x37, 0x2b,
	0x1d, 0x7a, 0x23, 0x12, 0xdb, 0x66, 0x97, 0xff, 0x5a, 0x00, 0xa5, 0x2b, 0xb1, 0x06, 0xbb, 0xc0,
	0x1d, 0x85, 0x6b, 0x41, 0x53, 0xbe, 0xfc, 0x85, 0xe1, 0x5a, 0x19, 0xc5, 0xed, 0x88, 0x09, 0xae,
	0x81, 0xf7, 0x06, 0x4c, 0x48, 0xe1, 0xcf, 0xe9, 0xea, 0x63, 0x3e, 0xca, 0x55, 0xe0, 0x8e, 0xf6,
	0x7d, 0x1f, 0x14, 0xf3, 0xdc, 0xa7, 0xd3, 0xbf, 0xde, 0xdc, 0x45, 0x4b, 0x16, 0xd4, 0xf5, 0xa2,
	0xfc, 0x8f, 0x02, 0x98, 0xab, 0xd7, 0xa0, 0x0f, 0x6e, 0x91, 0x30, 0x54, 0x8d, 0xad, 0xb5, 0x4f,
	0xfe, 0x09, 0x3b, 0x60, 0x49, 0xc6, 0x62, 0x9c, 0x70, 0xe6, 0x2e, 0xa5, 0xb1, 0xa9, 0x73, 0x83,
	0x0e, 0xd0, 0x6e, 0xfb, 0x68, 0x74, 0xea, 0x45, 0x19, 0x8b, 0xd1, 0xb1, 0x76, 0x41, 0x89, 0xd3,
	0x3f, 0x64, 0x54, 0x8c, 0x0d, 0x3d, 0x3f, 0xb3, 0xee, 0x58, 0x8d, 0x7c, 0x9a, 0x79, 0x04, 0x16,
	0xf5, 0xfe, 0x21, 0x16, 0x51, 0x48, 0xf5, 0xe0, 0xe6, 0x22, 0x60, 0xa0, 0xa3, 0x28, 0xa4, 0xe5,
	0x7f, 0xde, 0x04, 0x2b, 0xd7, 0xe2, 0x15, 0x42, 0xe0, 0xe8, 0x02, 0x60, 0xae, 0xa8, 0x7f, 0xc3,
	0x3f, 0x15, 0xc0, 0x9a, 0x69, 0x4a, 0xe9, 0xb9, 0x54, 0x0d, 0xd6, 0xe0, 0x47, 0x3d, 0xe8, 0xd9,
	0x8b, 0x7e, 0xfb, 0x8b, 0xb3, 0x42, 0x45, 0x77, 0xb0, 0x0a, 0xe6, 0x09, 0x89, 0x6b, 0x99, 0x1c,
	0x30, 0x1e, 0xfd, 0xa8, 0xef, 0xa1, 0x47, 0x45, 0x2b, 0xb6, 0x77, 0x03, 0xad, 0x50, 0x2b, 0xa9,
	0x84, 0x7e, 0x54, 0x8b, 0x53, 0x4f, 0xd3, 0xe7, 0x69, 0x60, 0x4d, 0xf4, 0x3f, 0x3d, 0xcd, 0x6b,
	0x9e, 0x06, 0xff, 0xf1, 0x34, 0x6a, 0xb1, 0xfc, 0xaf, 0x39, 0xf0, 0xf4, 0xe7, 0xdd, 0x46, 0x39,
	0x50, 0x3e, 0x10, 0x58, 0x07, 0xb2, 0x9f, 0xca, 0xe8, 0x7a, 0x66, 0x56, 0xf6, 0x2c, 0x22, 0xfd,
	0x5b, 0xbd, 0x5f, 0x4a, 0xe4, 0x00, 0xa7, 0x9c, 0xf6, 0xa2, 0x73, 0x7d, 0xb9, 0x05, 0x04, 0x14,
	0x74, 0xa8, 0x11, 0x78, 0x0f, 0x2c, 0xf4, 0x48, 0x14, 0x63, 0x96, 0xd2, 0xc4, 0x3e, 0xaf, 0xab,
	0x80, 0x4e, 0x4a, 0x13, 0x35, 0x4b, 0xa9, 0x62, 0x9e, 0x09, 0xcc, 0x12, 0x4c, 0x39, 0x67, 0x5c,
	0x0f, 0xe4, 0x0b, 0xa8, 0x68, 0xe0, 0x4e, 0xd2, 0x54, 0x20, 0xfc, 0x1c, 0xf8, 0x51, 0x12, 0xc4,
	0x59, 0x48, 0xf1, 0x80, 0x12, 0x95, 0x9d, 0x71, 0x94, 0xe0, 0x60, 0x40, 0x83, 0x53, 0xff, 0xa6,
	0x8e, 0x9a, 0x75, 0xbb, 0xbe, 0x67, 0x96, 0xf7, 0x93, 0xba, 0x5a, 0x84, 0xbf, 0x01, 0xf7, 0x73,
	0x05, 0xc9, 0x70, 0x96, 0x0a, 0xc9, 0x29, 0x19, 0xaa, 0xdd, 0x48, 0x1c, 0xb3, 0x77, 0xfe, 0x2d,
	0xad, 0xec, 0x5b, 0x99, 0x2e, 0x3b, 0xb6, 0x12, 0x9d, 0xa4, 0xa6, 0xd6, 0xe1, 0x6f, 0xc1, 0x83,
	0x09, 0xfd, 0x90, 0xbd, 0x4b, 0xc6, 0x0c, 0x21, 0x4d, 0x2e, 0x7c, 0x57, 0x13, 0xdc, 0x1d, 0x11,
	0x34, 0x46, 0x22, 0x9d, 0xa4, 0x41, 0x93, 0x8b, 0xf2, 0x9f, 0x0b, 0x3f, 0x65, 0xf9, 0xc9, 0x97,
	0xfb, 0x85, 0x96, 0xbf, 0x64, 0xd8, 0xf9, 0xd9, 0x86, 0x75, 0xa6, 0x18, 0x76, 0x17, 0x00, 0x37,
	0xaf, 0x9e, 0x9b, 0x2d, 0xb0, 0x3e, 0x75, 0xb4, 0x86, 0x25, 0xb0, 0x78, 0x7c, 0x70, 0x74, 0xd8,
	0xac, 0xef, 0xbf, 0xda, 0x6f, 0x36, 0xbc, 0x1b, 0xf0, 0x16, 0x98, 0xef, 0xbc, 0x7a, 0xe5, 0x15,
	0xe0, 0x22, 0xb8, 0xd5, 0x68, 0xbe, 0xaa, 0x1d, 0xb7, 0xbb, 0xde, 0x1c, 0x04, 0xe0, 0xe6, 0x51,
	0x17, 0xed, 0xd7, 0xbb, 0xde, 0xfc, 0xe6, 0x53, 0x00, 0xd4, 0x3d, 0x6d, 0x25, 0x73, 0x81, 0x73,
	0xd0, 0x39, 0x68, 0x7a, 0x37, 0xe0, 0x32, 0x00, 0x6f, 0x8e, 0x75, 0x51, 0xe9, 0xb6, 0x8f, 0xbc,
	0xc2, 0xe6, 0x33, 0xb0, 0x72, 0x6d, 0x7a, 0x55, 0xe2, 0xdd, 0xe6, 0xb7, 0x5d, 0xef, 0x86, 0xfa,
	0xd5, 0x3a, 0xea, 0x1c, 0x78, 0x85, 0xcd, 0x1d, 0x50, 0xba, 0xd2, 0x66, 0x42, 0x08, 0x96, 0x1b,
	0x1d, 0x7c, 0xd0, 0xe9, 0xe2, 0xe3, 0xc3, 0xd7, 0xa8, 0xd6, 0x50, 0xfc, 0x8b, 0xe0, 0x56, 0xfe,
	0x51, 0x68, 0x39, 0x6e, 0xc1, 0x9b, 0x6b, 0xa9, 0x62, 0x36, 0xdf, 0x72, 0xdc, 0x79, 0xcf, 0x69,
	0x39, 0xee, 0xc7, 0xde, 0x76, 0xcb, 0x71, 0xef, 0x7a, 0xe5, 0x96, 0xe3, 0x3e, 0xf4, 0x1e, 0xb5,
	0x1c, 0x17, 0x78, 0x8b, 0x2d, 0xc7, 0x5d, 0xf4, 0x96, 0x5a, 0x8e, 0x5b, 0xf2, 0xbc, 0x96, 0xe3,
	0x7a, 0xde, 0x4a, 0xcb, 0x71, 0xa1, 0xb7, 0xda, 0x72, 0xdc, 0x55, 0x6f, 0xad, 0xe5, 0xb8, 0x6b,
	0xde, 0x7a, 0xcb, 0x71, 0xd7, 0xbd, 0xdb, 0x2d, 0xc7, 0xbd, 0xe3, 0xf9, 0x2d, 0xc7, 0x7d, 0xe0,
	0x3d, 0x6c, 0x39, 0xee, 0xa7, 0xde, 0x67, 0x2d, 0xc7, 0x7d, 0xe2, 0x3d, 0x6d, 0x39, 0xee, 0x53,
	0xef, 0x59, 0xcb, 0x71, 0x9f, 0x79, 0x5b, 0x08, 0x0e, 0xa3, 0x73, 0xca, 0x8d, 0x7b, 0xea, 0x79,
	0x85, 0x72, 0xb4, 0x6a, 0x30, 0x4e, 0xf5, 0xa8, 0x61, 0xc1, 0xf5, 0x7c, 0x96, 0x36, 0xfd, 0xb6,
	0xd1, 0x10, 0x68, 0x34, 0x62, 0x1b, 0x1d, 0xfd, 0x67, 0x95, 0x51, 0x14, 0xe8, 0xf6, 0xa4, 0x28,
	0x1e, 0x39, 0x00, 0x7a, 0xa2, 0xd2, 0x67, 0x40, 0xb8, 0x72, 0x53, 0x49, 0x63, 0x3a, 0xa4, 0x52,
	0x77, 0x2d, 0x42, 0x77, 0x48, 0xaa, 0x23, 0x48, 0x22, 0x79, 0x81, 0x16, 0x55, 0x22, 0xb2, 0xdb,
	0xa1, 0x15, 0x1e, 0x8e, 0xc7, 0x86, 0x90, 0xc6, 0xe4, 0x02, 0x15, 0xcd, 0x96, 0xb6, 0x64, 0xa0,
	0xfc, 0x2f, 0x03, 0xd3, 0xe6, 0xe9, 0x14, 0x7d, 0xe9, 0xac, 0x68, 0x49, 0x84, 0x02, 0x67, 0xa1,
	0xc0, 0x2a, 0xe2, 0xd1, 0x8a, 0xb8, 0x46, 0x78, 0xdb, 0x32, 0xa8, 0x15, 0xc9, 0x4e, 0x69, 0x82,
	0x87, 0x2c, 0x4b, 0x24, 0x82, 0x5a, 0x51, 0x50, 0x7c, 0xfa, 0x52, 0x60, 0x41, 0xf0, 0xef, 0xdf,
	0x49, 0x54, 0x96, 0x94, 0x0f, 0xf3, 0xc9, 0x2c, 0xe4, 0x6a, 0x6e, 0xcd, 0xff, 0x98, 0x44, 0x6b,
	0xb9, 0x4d, 0xac, 0x05, 0x4f, 0x88, 0x0c, 0x06, 0xc8, 0x9f, 0xfc, 0xc2, 0x43, 0x72, 0x8e, 0x69,
	0x22, 0x79, 0x44, 0x05, 0x5a, 0xbf, 0xb6, 0xa2, 0x4a, 0xd4, 0xe6, 0xdf, 0x0b, 0x60, 0x69, 0x72,
	0x40, 0xff, 0x7f, 0x96, 0xcb, 0x43, 0xb0, 0x26, 0xb2, 0x13, 0x11, 0xf0, 0xe8, 0x84, 0x86, 0x98,
	0xd3, 0xfc, 0xcf, 0x84, 0xf9, 0x8d, 0xf9, 0xad, 0xe5, 0x9d, 0x07, 0x53, 0x0b, 0x02, 0xb2, 0x52,
	0x68, 0x75, 0xac, 0x9a, 0x63, 0x62, 0xf3, 0x6b, 0xb0, 0x38, 0xd1, 0x8b, 0xa9, 0x5c, 0x2c, 0x68,
	0xc0, 0xa9, 0x1d, 0x8e, 0xcc, 0x7d, 0x80, 0x81, 0xf4, 0x3c, 0x74, 0x0f, 0x2c, 0xa8, 0x49, 0x51,
	0xcf, 0xad, 0xb6, 0xdb, 0x70, 0xc3, 0x44, 0xe8, 0x91, 0xf5, 0xf9, 0x06, 0x70, 0x73, 0x66, 0xb8,
	0x06, 0xbc, 0xbc, 0xe9, 0xcb, 0x5b, 0x45, 0xef, 0xc6, 0xee, 0xfd, 0xef, 0xcb, 0xe6, 0x8c, 0xe6,
	0x3f, 0xdb, 0xea, 0xa5, 0x7f, 0x81, 0x4f, 0x6e, 0xea, 0x62, 0xff, 0xe2, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x29, 0x50, 0x81, 0x67, 0x8e, 0x16, 0x00, 0x00,
}
