// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesh/v1alpha1/proxy.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	v1alpha3 "istio.io/api/networking/v1alpha3"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AuthenticationPolicy defines how the proxy is authenticated when it connects to the control plane.
// It can be set for two different scopes, mesh-wide or set on a per-pod basis using the ProxyConfig annotation.
// Mesh policy cannot be INHERIT.
type AuthenticationPolicy int32

const (
	// Do not encrypt proxy to control plane traffic.
	AuthenticationPolicy_NONE AuthenticationPolicy = 0
	// Proxy to control plane traffic is wrapped into mutual TLS connections.
	AuthenticationPolicy_MUTUAL_TLS AuthenticationPolicy = 1
	// Use the policy defined by the parent scope. Should not be used for mesh
	// policy.
	AuthenticationPolicy_INHERIT AuthenticationPolicy = 1000
)

var AuthenticationPolicy_name = map[int32]string{
	0:    "NONE",
	1:    "MUTUAL_TLS",
	1000: "INHERIT",
}

var AuthenticationPolicy_value = map[string]int32{
	"NONE":       0,
	"MUTUAL_TLS": 1,
	"INHERIT":    1000,
}

func (x AuthenticationPolicy) String() string {
	return proto.EnumName(AuthenticationPolicy_name, int32(x))
}

func (AuthenticationPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0}
}

// TraceContext selects the context propagation headers used for
// distributed tracing.
type Tracing_OpenCensusAgent_TraceContext int32

const (
	// $hide_from_docs
	// Unspecified context. Should not be used for now, but added to reserve
	// the 0 enum value if TraceContext is used outside of a repeated field.
	Tracing_OpenCensusAgent_UNSPECIFIED Tracing_OpenCensusAgent_TraceContext = 0
	// Use W3C Trace Context propagation using the `traceparent` HTTP header.
	// See the
	// [Trace Context documentation](https://www.w3.org/TR/trace-context/) for details.
	Tracing_OpenCensusAgent_W3C_TRACE_CONTEXT Tracing_OpenCensusAgent_TraceContext = 1
	// Use gRPC binary context propagation using the `grpc-trace-bin` http header.
	Tracing_OpenCensusAgent_GRPC_BIN Tracing_OpenCensusAgent_TraceContext = 2
	// Use Cloud Trace context propagation using the
	// `X-Cloud-Trace-Context` http header.
	Tracing_OpenCensusAgent_CLOUD_TRACE_CONTEXT Tracing_OpenCensusAgent_TraceContext = 3
	// Use multi-header B3 context propagation using the `X-B3-TraceId`,
	// `X-B3-SpanId`, and `X-B3-Sampled` HTTP headers. See
	// [B3 header propagation README](https://github.com/openzipkin/b3-propagation)
	// for details.
	Tracing_OpenCensusAgent_B3 Tracing_OpenCensusAgent_TraceContext = 4
)

var Tracing_OpenCensusAgent_TraceContext_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "W3C_TRACE_CONTEXT",
	2: "GRPC_BIN",
	3: "CLOUD_TRACE_CONTEXT",
	4: "B3",
}

var Tracing_OpenCensusAgent_TraceContext_value = map[string]int32{
	"UNSPECIFIED":         0,
	"W3C_TRACE_CONTEXT":   1,
	"GRPC_BIN":            2,
	"CLOUD_TRACE_CONTEXT": 3,
	"B3":                  4,
}

func (x Tracing_OpenCensusAgent_TraceContext) String() string {
	return proto.EnumName(Tracing_OpenCensusAgent_TraceContext_name, int32(x))
}

func (Tracing_OpenCensusAgent_TraceContext) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 4, 0}
}

// $hide_from_docs
// ForwardClientCertDetails controls how the x-forwarded-client-cert (XFCC)
// header is handled by the gateway proxy.
// See [Envoy XFCC](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-enum-config-filter-network-http-connection-manager-v2-httpconnectionmanager-forwardclientcertdetails)
// header handling for more details.
type Topology_ForwardClientCertDetails int32

const (
	// Field is not set
	Topology_UNDEFINED Topology_ForwardClientCertDetails = 0
	// Do not send the XFCC header to the next hop. This is the default value.
	Topology_SANITIZE Topology_ForwardClientCertDetails = 1
	// When the client connection is mTLS (Mutual TLS), forward the XFCC header
	// in the request.
	Topology_FORWARD_ONLY Topology_ForwardClientCertDetails = 2
	// When the client connection is mTLS, append the client certificate
	// information to the request’s XFCC header and forward it.
	Topology_APPEND_FORWARD Topology_ForwardClientCertDetails = 3
	// When the client connection is mTLS, reset the XFCC header with the client
	// certificate information and send it to the next hop.
	Topology_SANITIZE_SET Topology_ForwardClientCertDetails = 4
	// Always forward the XFCC header in the request, regardless of whether the
	// client connection is mTLS.
	Topology_ALWAYS_FORWARD_ONLY Topology_ForwardClientCertDetails = 5
)

var Topology_ForwardClientCertDetails_name = map[int32]string{
	0: "UNDEFINED",
	1: "SANITIZE",
	2: "FORWARD_ONLY",
	3: "APPEND_FORWARD",
	4: "SANITIZE_SET",
	5: "ALWAYS_FORWARD_ONLY",
}

var Topology_ForwardClientCertDetails_value = map[string]int32{
	"UNDEFINED":           0,
	"SANITIZE":            1,
	"FORWARD_ONLY":        2,
	"APPEND_FORWARD":      3,
	"SANITIZE_SET":        4,
	"ALWAYS_FORWARD_ONLY": 5,
}

func (x Topology_ForwardClientCertDetails) String() string {
	return proto.EnumName(Topology_ForwardClientCertDetails_name, int32(x))
}

func (Topology_ForwardClientCertDetails) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{2, 0}
}

// The mode used to redirect inbound traffic to Envoy.
// This setting has no effect on outbound traffic: iptables `REDIRECT` is always used for
// outbound connections.
type ProxyConfig_InboundInterceptionMode int32

const (
	// The `REDIRECT` mode uses iptables `REDIRECT` to `NAT` and redirect to Envoy. This mode loses
	// source IP addresses during redirection.
	ProxyConfig_REDIRECT ProxyConfig_InboundInterceptionMode = 0
	// The `TPROXY` mode uses iptables `TPROXY` to redirect to Envoy. This mode preserves both the
	// source and destination IP addresses and ports, so that they can be used for advanced
	// filtering and manipulation. This mode also configures the sidecar to run with the
	// `CAP_NET_ADMIN` capability, which is required to use `TPROXY`.
	ProxyConfig_TPROXY ProxyConfig_InboundInterceptionMode = 1
)

var ProxyConfig_InboundInterceptionMode_name = map[int32]string{
	0: "REDIRECT",
	1: "TPROXY",
}

var ProxyConfig_InboundInterceptionMode_value = map[string]int32{
	"REDIRECT": 0,
	"TPROXY":   1,
}

func (x ProxyConfig_InboundInterceptionMode) String() string {
	return proto.EnumName(ProxyConfig_InboundInterceptionMode_name, int32(x))
}

func (ProxyConfig_InboundInterceptionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{3, 0}
}

// Tracing defines configuration for the tracing performed by Envoy instances.
type Tracing struct {
	// The tracer implementation to be used by Envoy.
	//
	// Types that are valid to be assigned to Tracer:
	//	*Tracing_Zipkin_
	//	*Tracing_Lightstep_
	//	*Tracing_Datadog_
	//	*Tracing_Stackdriver_
	//	*Tracing_OpenCensusAgent_
	Tracer isTracing_Tracer `protobuf_oneof:"tracer"`
	// Configures the custom tags to be added to active span by all proxies (i.e. sidecars
	// and gateways).
	// The key represents the name of the tag.
	// Ex:
	// ```yaml
	// custom_tags:
	//   new_tag_name:
	//     header:
	//       name: custom-http-header-name
	//       default_value: defaulted-value-from-custom-header
	// ```
	// $hide_from_docs
	CustomTags map[string]*Tracing_CustomTag `protobuf:"bytes,5,rep,name=custom_tags,json=customTags,proto3" json:"customTags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Configures the maximum length of the request path to extract and include in the
	// HttpUrl tag. Used to truncate length request paths to meet the needs of tracing
	// backend. If not set, then a length of 256 will be used.
	// $hide_from_docs
	MaxPathTagLength uint32 `protobuf:"varint,6,opt,name=max_path_tag_length,json=maxPathTagLength,proto3" json:"maxPathTagLength,omitempty"`
	// The percentage of requests (0.0 - 100.0) that will be randomly selected for trace generation,
	// if not requested by the client or not forced. Default is 1.0.
	Sampling float64 `protobuf:"fixed64,7,opt,name=sampling,proto3" json:"sampling,omitempty"`
	// Use the tls_settings to specify the tls mode to use. If the remote tracing service
	// uses Istio mutual TLS and shares the root CA with Pilot, specify the TLS
	// mode as `ISTIO_MUTUAL`.
	TlsSettings          *v1alpha3.ClientTLSSettings `protobuf:"bytes,8,opt,name=tls_settings,json=tlsSettings,proto3" json:"tlsSettings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Tracing) Reset()         { *m = Tracing{} }
func (m *Tracing) String() string { return proto.CompactTextString(m) }
func (*Tracing) ProtoMessage()    {}
func (*Tracing) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0}
}

func (m *Tracing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing.Unmarshal(m, b)
}
func (m *Tracing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing.Marshal(b, m, deterministic)
}
func (m *Tracing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing.Merge(m, src)
}
func (m *Tracing) XXX_Size() int {
	return xxx_messageInfo_Tracing.Size(m)
}
func (m *Tracing) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing proto.InternalMessageInfo

type isTracing_Tracer interface {
	isTracing_Tracer()
}

type Tracing_Zipkin_ struct {
	Zipkin *Tracing_Zipkin `protobuf:"bytes,1,opt,name=zipkin,proto3,oneof"`
}

type Tracing_Lightstep_ struct {
	Lightstep *Tracing_Lightstep `protobuf:"bytes,2,opt,name=lightstep,proto3,oneof"`
}

type Tracing_Datadog_ struct {
	Datadog *Tracing_Datadog `protobuf:"bytes,3,opt,name=datadog,proto3,oneof"`
}

type Tracing_Stackdriver_ struct {
	Stackdriver *Tracing_Stackdriver `protobuf:"bytes,4,opt,name=stackdriver,proto3,oneof"`
}

type Tracing_OpenCensusAgent_ struct {
	OpenCensusAgent *Tracing_OpenCensusAgent `protobuf:"bytes,9,opt,name=open_census_agent,json=openCensusAgent,proto3,oneof"`
}

func (*Tracing_Zipkin_) isTracing_Tracer() {}

func (*Tracing_Lightstep_) isTracing_Tracer() {}

func (*Tracing_Datadog_) isTracing_Tracer() {}

func (*Tracing_Stackdriver_) isTracing_Tracer() {}

func (*Tracing_OpenCensusAgent_) isTracing_Tracer() {}

func (m *Tracing) GetTracer() isTracing_Tracer {
	if m != nil {
		return m.Tracer
	}
	return nil
}

func (m *Tracing) GetZipkin() *Tracing_Zipkin {
	if x, ok := m.GetTracer().(*Tracing_Zipkin_); ok {
		return x.Zipkin
	}
	return nil
}

func (m *Tracing) GetLightstep() *Tracing_Lightstep {
	if x, ok := m.GetTracer().(*Tracing_Lightstep_); ok {
		return x.Lightstep
	}
	return nil
}

func (m *Tracing) GetDatadog() *Tracing_Datadog {
	if x, ok := m.GetTracer().(*Tracing_Datadog_); ok {
		return x.Datadog
	}
	return nil
}

func (m *Tracing) GetStackdriver() *Tracing_Stackdriver {
	if x, ok := m.GetTracer().(*Tracing_Stackdriver_); ok {
		return x.Stackdriver
	}
	return nil
}

func (m *Tracing) GetOpenCensusAgent() *Tracing_OpenCensusAgent {
	if x, ok := m.GetTracer().(*Tracing_OpenCensusAgent_); ok {
		return x.OpenCensusAgent
	}
	return nil
}

func (m *Tracing) GetCustomTags() map[string]*Tracing_CustomTag {
	if m != nil {
		return m.CustomTags
	}
	return nil
}

func (m *Tracing) GetMaxPathTagLength() uint32 {
	if m != nil {
		return m.MaxPathTagLength
	}
	return 0
}

func (m *Tracing) GetSampling() float64 {
	if m != nil {
		return m.Sampling
	}
	return 0
}

func (m *Tracing) GetTlsSettings() *v1alpha3.ClientTLSSettings {
	if m != nil {
		return m.TlsSettings
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tracing) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tracing_Zipkin_)(nil),
		(*Tracing_Lightstep_)(nil),
		(*Tracing_Datadog_)(nil),
		(*Tracing_Stackdriver_)(nil),
		(*Tracing_OpenCensusAgent_)(nil),
	}
}

// Zipkin defines configuration for a Zipkin tracer.
type Tracing_Zipkin struct {
	// Address of the Zipkin service (e.g. _zipkin:9411_).
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_Zipkin) Reset()         { *m = Tracing_Zipkin{} }
func (m *Tracing_Zipkin) String() string { return proto.CompactTextString(m) }
func (*Tracing_Zipkin) ProtoMessage()    {}
func (*Tracing_Zipkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 0}
}

func (m *Tracing_Zipkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Zipkin.Unmarshal(m, b)
}
func (m *Tracing_Zipkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Zipkin.Marshal(b, m, deterministic)
}
func (m *Tracing_Zipkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Zipkin.Merge(m, src)
}
func (m *Tracing_Zipkin) XXX_Size() int {
	return xxx_messageInfo_Tracing_Zipkin.Size(m)
}
func (m *Tracing_Zipkin) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Zipkin.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Zipkin proto.InternalMessageInfo

func (m *Tracing_Zipkin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Defines configuration for a Lightstep tracer.
type Tracing_Lightstep struct {
	// Address of the Lightstep Satellite pool.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The Lightstep access token.
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_Lightstep) Reset()         { *m = Tracing_Lightstep{} }
func (m *Tracing_Lightstep) String() string { return proto.CompactTextString(m) }
func (*Tracing_Lightstep) ProtoMessage()    {}
func (*Tracing_Lightstep) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 1}
}

func (m *Tracing_Lightstep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Lightstep.Unmarshal(m, b)
}
func (m *Tracing_Lightstep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Lightstep.Marshal(b, m, deterministic)
}
func (m *Tracing_Lightstep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Lightstep.Merge(m, src)
}
func (m *Tracing_Lightstep) XXX_Size() int {
	return xxx_messageInfo_Tracing_Lightstep.Size(m)
}
func (m *Tracing_Lightstep) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Lightstep.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Lightstep proto.InternalMessageInfo

func (m *Tracing_Lightstep) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Tracing_Lightstep) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// Datadog defines configuration for a Datadog tracer.
type Tracing_Datadog struct {
	// Address of the Datadog Agent.
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_Datadog) Reset()         { *m = Tracing_Datadog{} }
func (m *Tracing_Datadog) String() string { return proto.CompactTextString(m) }
func (*Tracing_Datadog) ProtoMessage()    {}
func (*Tracing_Datadog) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 2}
}

func (m *Tracing_Datadog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Datadog.Unmarshal(m, b)
}
func (m *Tracing_Datadog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Datadog.Marshal(b, m, deterministic)
}
func (m *Tracing_Datadog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Datadog.Merge(m, src)
}
func (m *Tracing_Datadog) XXX_Size() int {
	return xxx_messageInfo_Tracing_Datadog.Size(m)
}
func (m *Tracing_Datadog) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Datadog.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Datadog proto.InternalMessageInfo

func (m *Tracing_Datadog) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Stackdriver defines configuration for a Stackdriver tracer.
// See [Envoy's OpenCensus trace configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opencensus.proto)
// and
// [OpenCensus trace config](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/trace/v1/trace_config.proto) for details.
type Tracing_Stackdriver struct {
	// debug enables trace output to stdout.
	// $hide_from_docs
	Debug bool `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	// The global default max number of attributes per span.
	// default is 200.
	// $hide_from_docs
	MaxNumberOfAttributes *wrappers.Int64Value `protobuf:"bytes,2,opt,name=max_number_of_attributes,json=maxNumberOfAttributes,proto3" json:"maxNumberOfAttributes,omitempty"`
	// The global default max number of annotation events per span.
	// default is 200.
	// $hide_from_docs
	MaxNumberOfAnnotations *wrappers.Int64Value `protobuf:"bytes,3,opt,name=max_number_of_annotations,json=maxNumberOfAnnotations,proto3" json:"maxNumberOfAnnotations,omitempty"`
	// The global default max number of message events per span.
	// default is 200.
	// $hide_from_docs
	MaxNumberOfMessageEvents *wrappers.Int64Value `protobuf:"bytes,4,opt,name=max_number_of_message_events,json=maxNumberOfMessageEvents,proto3" json:"maxNumberOfMessageEvents,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}             `json:"-"`
	XXX_unrecognized         []byte               `json:"-"`
	XXX_sizecache            int32                `json:"-"`
}

func (m *Tracing_Stackdriver) Reset()         { *m = Tracing_Stackdriver{} }
func (m *Tracing_Stackdriver) String() string { return proto.CompactTextString(m) }
func (*Tracing_Stackdriver) ProtoMessage()    {}
func (*Tracing_Stackdriver) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 3}
}

func (m *Tracing_Stackdriver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Stackdriver.Unmarshal(m, b)
}
func (m *Tracing_Stackdriver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Stackdriver.Marshal(b, m, deterministic)
}
func (m *Tracing_Stackdriver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Stackdriver.Merge(m, src)
}
func (m *Tracing_Stackdriver) XXX_Size() int {
	return xxx_messageInfo_Tracing_Stackdriver.Size(m)
}
func (m *Tracing_Stackdriver) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Stackdriver.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Stackdriver proto.InternalMessageInfo

func (m *Tracing_Stackdriver) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *Tracing_Stackdriver) GetMaxNumberOfAttributes() *wrappers.Int64Value {
	if m != nil {
		return m.MaxNumberOfAttributes
	}
	return nil
}

func (m *Tracing_Stackdriver) GetMaxNumberOfAnnotations() *wrappers.Int64Value {
	if m != nil {
		return m.MaxNumberOfAnnotations
	}
	return nil
}

func (m *Tracing_Stackdriver) GetMaxNumberOfMessageEvents() *wrappers.Int64Value {
	if m != nil {
		return m.MaxNumberOfMessageEvents
	}
	return nil
}

// OpenCensusAgent defines configuration for an OpenCensus tracer writing to
// an OpenCensus agent backend. See
// [Envoy's OpenCensus trace configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opencensus.proto)
// and
// [OpenCensus trace config](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/trace/v1/trace_config.proto)
// for details.
type Tracing_OpenCensusAgent struct {
	// gRPC address for the OpenCensus agent (e.g. dns://authority/host:port or
	// unix:path). See [gRPC naming
	// docs](https://github.com/grpc/grpc/blob/master/doc/naming.md) for
	// details.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Specifies the set of context propagation headers used for distributed
	// tracing. Default is `["W3C_TRACE_CONTEXT"]`. If multiple values are specified,
	// the proxy will attempt to read each header for each request and will
	// write all headers.
	Context              []Tracing_OpenCensusAgent_TraceContext `protobuf:"varint,2,rep,packed,name=context,proto3,enum=istio.mesh.v1alpha1.Tracing_OpenCensusAgent_TraceContext" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *Tracing_OpenCensusAgent) Reset()         { *m = Tracing_OpenCensusAgent{} }
func (m *Tracing_OpenCensusAgent) String() string { return proto.CompactTextString(m) }
func (*Tracing_OpenCensusAgent) ProtoMessage()    {}
func (*Tracing_OpenCensusAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 4}
}

func (m *Tracing_OpenCensusAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_OpenCensusAgent.Unmarshal(m, b)
}
func (m *Tracing_OpenCensusAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_OpenCensusAgent.Marshal(b, m, deterministic)
}
func (m *Tracing_OpenCensusAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_OpenCensusAgent.Merge(m, src)
}
func (m *Tracing_OpenCensusAgent) XXX_Size() int {
	return xxx_messageInfo_Tracing_OpenCensusAgent.Size(m)
}
func (m *Tracing_OpenCensusAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_OpenCensusAgent.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_OpenCensusAgent proto.InternalMessageInfo

func (m *Tracing_OpenCensusAgent) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Tracing_OpenCensusAgent) GetContext() []Tracing_OpenCensusAgent_TraceContext {
	if m != nil {
		return m.Context
	}
	return nil
}

// Configure custom tags that will be added to any active span.
// Tags can be generated via literals, environment variables or an incoming request header.
// $hide_from_docs
type Tracing_CustomTag struct {
	// Specify how to populate the value in a custom tag
	//
	// Types that are valid to be assigned to Type:
	//	*Tracing_CustomTag_Literal
	//	*Tracing_CustomTag_Environment
	//	*Tracing_CustomTag_Header
	Type                 isTracing_CustomTag_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Tracing_CustomTag) Reset()         { *m = Tracing_CustomTag{} }
func (m *Tracing_CustomTag) String() string { return proto.CompactTextString(m) }
func (*Tracing_CustomTag) ProtoMessage()    {}
func (*Tracing_CustomTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 5}
}

func (m *Tracing_CustomTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_CustomTag.Unmarshal(m, b)
}
func (m *Tracing_CustomTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_CustomTag.Marshal(b, m, deterministic)
}
func (m *Tracing_CustomTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_CustomTag.Merge(m, src)
}
func (m *Tracing_CustomTag) XXX_Size() int {
	return xxx_messageInfo_Tracing_CustomTag.Size(m)
}
func (m *Tracing_CustomTag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_CustomTag.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_CustomTag proto.InternalMessageInfo

type isTracing_CustomTag_Type interface {
	isTracing_CustomTag_Type()
}

type Tracing_CustomTag_Literal struct {
	Literal *Tracing_Literal `protobuf:"bytes,1,opt,name=literal,proto3,oneof"`
}

type Tracing_CustomTag_Environment struct {
	Environment *Tracing_Environment `protobuf:"bytes,2,opt,name=environment,proto3,oneof"`
}

type Tracing_CustomTag_Header struct {
	Header *Tracing_RequestHeader `protobuf:"bytes,3,opt,name=header,proto3,oneof"`
}

func (*Tracing_CustomTag_Literal) isTracing_CustomTag_Type() {}

func (*Tracing_CustomTag_Environment) isTracing_CustomTag_Type() {}

func (*Tracing_CustomTag_Header) isTracing_CustomTag_Type() {}

func (m *Tracing_CustomTag) GetType() isTracing_CustomTag_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Tracing_CustomTag) GetLiteral() *Tracing_Literal {
	if x, ok := m.GetType().(*Tracing_CustomTag_Literal); ok {
		return x.Literal
	}
	return nil
}

func (m *Tracing_CustomTag) GetEnvironment() *Tracing_Environment {
	if x, ok := m.GetType().(*Tracing_CustomTag_Environment); ok {
		return x.Environment
	}
	return nil
}

func (m *Tracing_CustomTag) GetHeader() *Tracing_RequestHeader {
	if x, ok := m.GetType().(*Tracing_CustomTag_Header); ok {
		return x.Header
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tracing_CustomTag) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tracing_CustomTag_Literal)(nil),
		(*Tracing_CustomTag_Environment)(nil),
		(*Tracing_CustomTag_Header)(nil),
	}
}

// Literal type represents a static value.
// $hide_from_docs
type Tracing_Literal struct {
	// Static literal value used to populate the tag value.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_Literal) Reset()         { *m = Tracing_Literal{} }
func (m *Tracing_Literal) String() string { return proto.CompactTextString(m) }
func (*Tracing_Literal) ProtoMessage()    {}
func (*Tracing_Literal) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 6}
}

func (m *Tracing_Literal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Literal.Unmarshal(m, b)
}
func (m *Tracing_Literal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Literal.Marshal(b, m, deterministic)
}
func (m *Tracing_Literal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Literal.Merge(m, src)
}
func (m *Tracing_Literal) XXX_Size() int {
	return xxx_messageInfo_Tracing_Literal.Size(m)
}
func (m *Tracing_Literal) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Literal.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Literal proto.InternalMessageInfo

func (m *Tracing_Literal) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Environment is the proxy's environment variable to be used for populating the custom span tag.
// $hide_from_docs
type Tracing_Environment struct {
	// Name of the environment variable used to populate the tag's value
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When the environment variable is not found,
	// the tag's value will be populated with this default value if specified,
	// otherwise the tag will not be populated.
	DefaultValue         string   `protobuf:"bytes,2,opt,name=default_value,json=defaultValue,proto3" json:"defaultValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_Environment) Reset()         { *m = Tracing_Environment{} }
func (m *Tracing_Environment) String() string { return proto.CompactTextString(m) }
func (*Tracing_Environment) ProtoMessage()    {}
func (*Tracing_Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 7}
}

func (m *Tracing_Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Environment.Unmarshal(m, b)
}
func (m *Tracing_Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Environment.Marshal(b, m, deterministic)
}
func (m *Tracing_Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Environment.Merge(m, src)
}
func (m *Tracing_Environment) XXX_Size() int {
	return xxx_messageInfo_Tracing_Environment.Size(m)
}
func (m *Tracing_Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Environment proto.InternalMessageInfo

func (m *Tracing_Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tracing_Environment) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

// RequestHeader is the HTTP request header which will be used to populate the span tag.
// A default value can be configured if the header does not exist.
// $hide_from_docs
type Tracing_RequestHeader struct {
	// HTTP header name used to obtain the value from to populate the tag value.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Default value to be used for the tag when the named HTTP header does not exist.
	// The tag will be skipped if no default value is provided.
	DefaultValue         string   `protobuf:"bytes,2,opt,name=default_value,json=defaultValue,proto3" json:"defaultValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracing_RequestHeader) Reset()         { *m = Tracing_RequestHeader{} }
func (m *Tracing_RequestHeader) String() string { return proto.CompactTextString(m) }
func (*Tracing_RequestHeader) ProtoMessage()    {}
func (*Tracing_RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{0, 8}
}

func (m *Tracing_RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_RequestHeader.Unmarshal(m, b)
}
func (m *Tracing_RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_RequestHeader.Marshal(b, m, deterministic)
}
func (m *Tracing_RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_RequestHeader.Merge(m, src)
}
func (m *Tracing_RequestHeader) XXX_Size() int {
	return xxx_messageInfo_Tracing_RequestHeader.Size(m)
}
func (m *Tracing_RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_RequestHeader proto.InternalMessageInfo

func (m *Tracing_RequestHeader) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tracing_RequestHeader) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

// SDS defines secret discovery service(SDS) configuration to be used by the proxy.
// For workload, its values are set in sidecar injector(passed as arguments to istio-proxy container).
// For pilot/mixer, it's passed as arguments to istio-proxy container in pilot/mixer deployment yaml files directly.
type SDS struct {
	// True if SDS is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Path of k8s service account JWT path.
	K8SSaJwtPath         string   `protobuf:"bytes,2,opt,name=k8s_sa_jwt_path,json=k8sSaJwtPath,proto3" json:"k8sSaJwtPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDS) Reset()         { *m = SDS{} }
func (m *SDS) String() string { return proto.CompactTextString(m) }
func (*SDS) ProtoMessage()    {}
func (*SDS) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{1}
}

func (m *SDS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDS.Unmarshal(m, b)
}
func (m *SDS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDS.Marshal(b, m, deterministic)
}
func (m *SDS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDS.Merge(m, src)
}
func (m *SDS) XXX_Size() int {
	return xxx_messageInfo_SDS.Size(m)
}
func (m *SDS) XXX_DiscardUnknown() {
	xxx_messageInfo_SDS.DiscardUnknown(m)
}

var xxx_messageInfo_SDS proto.InternalMessageInfo

func (m *SDS) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *SDS) GetK8SSaJwtPath() string {
	if m != nil {
		return m.K8SSaJwtPath
	}
	return ""
}

// $hide_from_docs
// Topology describes the configuration for relative location of a proxy with
// respect to intermediate trusted proxies and the client. These settings
// control how the client attributes are retrieved from the incoming traffic by
// the gateway proxy and propagated to the upstream services in the cluster.
type Topology struct {
	// $hide_from_docs
	// Number of trusted proxies deployed in front of the Istio gateway proxy.
	// When this option is set to value N greater than zero, the trusted client
	// address is assumed to be the Nth address from the right end of the
	// X-Forwarded-For (XFF) header from the incoming request. If the
	// X-Forwarded-For (XFF) header is missing or has fewer than N addresses, the
	// gateway proxy falls back to using the immediate downstream connection's
	// source address as the trusted client address.
	// Note that the gateway proxy will append the downstream connection's source
	// address to the X-Forwarded-For (XFF) address and set the
	// X-Envoy-External-Address header to the trusted client address before
	// forwarding it to the upstream services in the cluster.
	// The default value of num_trusted_proxies is 0.
	// See [Envoy XFF] (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for)
	// header handling for more details.
	NumTrustedProxies uint32 `protobuf:"varint,1,opt,name=num_trusted_proxies,json=numTrustedProxies,proto3" json:"numTrustedProxies,omitempty"`
	// $hide_from_docs
	// Configures how the gateway proxy handles x-forwarded-client-cert (XFCC)
	// header in the incoming request.
	ForwardClientCertDetails Topology_ForwardClientCertDetails `protobuf:"varint,2,opt,name=forward_client_cert_details,json=forwardClientCertDetails,proto3,enum=istio.mesh.v1alpha1.Topology_ForwardClientCertDetails" json:"forwardClientCertDetails,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                          `json:"-"`
	XXX_unrecognized         []byte                            `json:"-"`
	XXX_sizecache            int32                             `json:"-"`
}

func (m *Topology) Reset()         { *m = Topology{} }
func (m *Topology) String() string { return proto.CompactTextString(m) }
func (*Topology) ProtoMessage()    {}
func (*Topology) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{2}
}

func (m *Topology) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topology.Unmarshal(m, b)
}
func (m *Topology) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topology.Marshal(b, m, deterministic)
}
func (m *Topology) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topology.Merge(m, src)
}
func (m *Topology) XXX_Size() int {
	return xxx_messageInfo_Topology.Size(m)
}
func (m *Topology) XXX_DiscardUnknown() {
	xxx_messageInfo_Topology.DiscardUnknown(m)
}

var xxx_messageInfo_Topology proto.InternalMessageInfo

func (m *Topology) GetNumTrustedProxies() uint32 {
	if m != nil {
		return m.NumTrustedProxies
	}
	return 0
}

func (m *Topology) GetForwardClientCertDetails() Topology_ForwardClientCertDetails {
	if m != nil {
		return m.ForwardClientCertDetails
	}
	return Topology_UNDEFINED
}

// ProxyConfig defines variables for individual Envoy instances.
type ProxyConfig struct {
	// Path to the generated configuration file directory.
	// Proxy agent generates the actual configuration and stores it in this directory.
	ConfigPath string `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"configPath,omitempty"`
	// Path to the proxy binary
	BinaryPath string `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath,proto3" json:"binaryPath,omitempty"`
	// Service cluster defines the name for the `service_cluster` that is
	// shared by all Envoy instances. This setting corresponds to
	// `--service-cluster` flag in Envoy.  In a typical Envoy deployment, the
	// `service-cluster` flag is used to identify the caller, for
	// source-based routing scenarios.
	//
	// Since Istio does not assign a local `service/service` version to each
	// Envoy instance, the name is same for all of them.  However, the
	// source/caller's identity (e.g., IP address) is encoded in the
	// `--service-node` flag when launching Envoy.  When the RDS service
	// receives API calls from Envoy, it uses the value of the `service-node`
	// flag to compute routes that are relative to the service instances
	// located at that IP address.
	ServiceCluster string `protobuf:"bytes,3,opt,name=service_cluster,json=serviceCluster,proto3" json:"serviceCluster,omitempty"`
	// The time in seconds that Envoy will drain connections during a hot
	// restart. MUST be >=1s (e.g., _1s/1m/1h_)
	// Default drain duration is `45s`.
	DrainDuration *duration.Duration `protobuf:"bytes,4,opt,name=drain_duration,json=drainDuration,proto3" json:"drainDuration,omitempty"`
	// The time in seconds that Envoy will wait before shutting down the
	// parent process during a hot restart. MUST be >=1s (e.g., `1s/1m/1h`).
	// MUST BE greater than `drain_duration` parameter.
	// Default shutdown duration is `60s`.
	ParentShutdownDuration *duration.Duration `protobuf:"bytes,5,opt,name=parent_shutdown_duration,json=parentShutdownDuration,proto3" json:"parentShutdownDuration,omitempty"`
	// Address of the discovery service exposing xDS with mTLS connection.
	// The inject configuration may override this value.
	DiscoveryAddress string `protobuf:"bytes,6,opt,name=discovery_address,json=discoveryAddress,proto3" json:"discoveryAddress,omitempty"`
	// $hide_from_docs
	DiscoveryRefreshDelay *duration.Duration `protobuf:"bytes,7,opt,name=discovery_refresh_delay,json=discoveryRefreshDelay,proto3" json:"discoveryRefreshDelay,omitempty"` // Deprecated: Do not use.
	// Address of the Zipkin service (e.g. _zipkin:9411_).
	// DEPRECATED: Use [tracing][istio.mesh.v1alpha1.ProxyConfig.tracing] instead.
	ZipkinAddress string `protobuf:"bytes,8,opt,name=zipkin_address,json=zipkinAddress,proto3" json:"zipkinAddress,omitempty"` // Deprecated: Do not use.
	// IP Address and Port of a statsd UDP listener (e.g. `10.75.241.127:9125`).
	StatsdUdpAddress string `protobuf:"bytes,10,opt,name=statsd_udp_address,json=statsdUdpAddress,proto3" json:"statsdUdpAddress,omitempty"`
	// $hide_from_docs
	EnvoyMetricsServiceAddress string `protobuf:"bytes,20,opt,name=envoy_metrics_service_address,json=envoyMetricsServiceAddress,proto3" json:"envoyMetricsServiceAddress,omitempty"` // Deprecated: Do not use.
	// Port on which Envoy should listen for administrative commands.
	// Default port is `15000`.
	ProxyAdminPort int32 `protobuf:"varint,11,opt,name=proxy_admin_port,json=proxyAdminPort,proto3" json:"proxyAdminPort,omitempty"`
	// $hide_from_docs
	AvailabilityZone string `protobuf:"bytes,12,opt,name=availability_zone,json=availabilityZone,proto3" json:"availabilityZone,omitempty"` // Deprecated: Do not use.
	// AuthenticationPolicy defines how the proxy is authenticated when it connects to the control plane.
	// Default is set to `MUTUAL_TLS`.
	ControlPlaneAuthPolicy AuthenticationPolicy `protobuf:"varint,13,opt,name=control_plane_auth_policy,json=controlPlaneAuthPolicy,proto3,enum=istio.mesh.v1alpha1.AuthenticationPolicy" json:"controlPlaneAuthPolicy,omitempty"`
	// File path of custom proxy configuration, currently used by proxies
	// in front of Mixer and Pilot.
	CustomConfigFile string `protobuf:"bytes,14,opt,name=custom_config_file,json=customConfigFile,proto3" json:"customConfigFile,omitempty"`
	// Maximum length of name field in Envoy's metrics. The length of the name field
	// is determined by the length of a name field in a service and the set of labels that
	// comprise a particular version of the service. The default value is set to 189 characters.
	// Envoy's internal metrics take up 67 characters, for a total of 256 character name per metric.
	// Increase the value of this field if you find that the metrics from Envoys are truncated.
	StatNameLength int32 `protobuf:"varint,15,opt,name=stat_name_length,json=statNameLength,proto3" json:"statNameLength,omitempty"`
	// The number of worker threads to run.
	// If unset, this will be automatically determined based on CPU requests/limits.
	// If set to 0, all cores on the machine will be used.
	// Default is 2 worker threads.
	Concurrency *wrappers.Int32Value `protobuf:"bytes,16,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// Path to the proxy bootstrap template file
	ProxyBootstrapTemplatePath string `protobuf:"bytes,17,opt,name=proxy_bootstrap_template_path,json=proxyBootstrapTemplatePath,proto3" json:"proxyBootstrapTemplatePath,omitempty"`
	// The mode used to redirect inbound traffic to Envoy.
	InterceptionMode ProxyConfig_InboundInterceptionMode `protobuf:"varint,18,opt,name=interception_mode,json=interceptionMode,proto3,enum=istio.mesh.v1alpha1.ProxyConfig_InboundInterceptionMode" json:"interceptionMode,omitempty"`
	// Tracing configuration to be used by the proxy.
	Tracing *Tracing `protobuf:"bytes,19,opt,name=tracing,proto3" json:"tracing,omitempty"`
	// Secret Discovery Service(SDS) configuration to be used by the proxy.
	Sds *SDS `protobuf:"bytes,21,opt,name=sds,proto3" json:"sds,omitempty"`
	// Address of the service to which access logs from Envoys should be
	// sent. (e.g. `accesslog-service:15000`). See [Access Log
	// Service](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/accesslog/v2/als.proto)
	// for details about Envoy's gRPC Access Log Service API.
	EnvoyAccessLogService *RemoteService `protobuf:"bytes,22,opt,name=envoy_access_log_service,json=envoyAccessLogService,proto3" json:"envoyAccessLogService,omitempty"`
	// Address of the Envoy Metrics Service implementation (e.g. `metrics-service:15000`).
	// See [Metric Service](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/metrics_service.proto)
	// for details about Envoy's Metrics Service API.
	EnvoyMetricsService *RemoteService `protobuf:"bytes,23,opt,name=envoy_metrics_service,json=envoyMetricsService,proto3" json:"envoyMetricsService,omitempty"`
	// Additional environment variables for the proxy.
	// Names starting with `ISTIO_META_` will be included in the generated bootstrap and sent to the XDS server.
	ProxyMetadata map[string]string `protobuf:"bytes,24,rep,name=proxy_metadata,json=proxyMetadata,proto3" json:"proxyMetadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Port on which the agent should listen for administrative commands such as readiness probe.
	// Default is set to port `15020`.
	StatusPort int32 `protobuf:"varint,26,opt,name=status_port,json=statusPort,proto3" json:"statusPort,omitempty"`
	// An additional list of tags to extract from the in-proxy Istio telemetry. These extra tags can be
	// added by configuring the telemetry extension. Each additional tag needs to be present in this list.
	// Extra tags emitted by the telemetry extensions must be listed here so that they can be processed
	// and exposed as Prometheus metrics.
	ExtraStatTags []string `protobuf:"bytes,27,rep,name=extra_stat_tags,json=extraStatTags,proto3" json:"extraStatTags,omitempty"`
	// $hide_from_docs
	// Topology encapsulates the configuration which describes where the proxy is
	// located i.e. behind a (or N) trusted proxy (proxies) or directly exposed
	// to the internet. This configuration only effects gateways and is applied
	// to all the gateways in the cluster unless overriden via annotations of the
	// gateway workloads.
	GatewayTopology *Topology `protobuf:"bytes,28,opt,name=gateway_topology,json=gatewayTopology,proto3" json:"gatewayTopology,omitempty"`
	// The amount of time allowed for connections to complete on proxy shutdown.
	// On receiving `SIGTERM` or `SIGINT`, `istio-agent` tells the active Envoy to start draining,
	// preventing any new connections and allowing existing connections to complete. It then
	// sleeps for the `termination_drain_duration` and then kills any remaining active Envoy processes.
	// If not set, a default of `5s` will be applied.
	TerminationDrainDuration *duration.Duration `protobuf:"bytes,29,opt,name=termination_drain_duration,json=terminationDrainDuration,proto3" json:"terminationDrainDuration,omitempty"`
	// The unique identifier for the [service mesh](https://istio.io/docs/reference/glossary/#service-mesh)
	// All control planes running in the same service mesh should specify the same mesh ID.
	// Mesh ID is used to label telemetry reports for cases where telemetry from multiple meshes is mixed together.
	MeshId string `protobuf:"bytes,30,opt,name=mesh_id,json=meshId,proto3" json:"meshId,omitempty"`
	// VM Health Checking readiness probe. This health check config exactly mirrors the
	// kubernetes readiness probe configuration both in schema and logic.
	// Only one health check method of 3 can be set at a time.
	ReadinessProbe *v1alpha3.ReadinessProbe `protobuf:"bytes,31,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readinessProbe,omitempty"`
	// Proxy stats matcher defines configuration for reporting custom Envoy stats.
	// To reduce memory and CPU overhead from Envoy stats system, Istio proxies by
	// default create and expose only a subset of Envoy stats. This option is to
	// control creation of additional Envoy stats with prefix, suffix, and regex
	// expressions match on the name of the stats. This replaces the stats
	// inclusion annotations
	// (`sidecar.istio.io/statsInclusionPrefixes`,
	// `sidecar.istio.io/statsInclusionRegexps`, and
	// `sidecar.istio.io/statsInclusionSuffixes`). For example, to enable stats
	// for circuit breaker, retry, and upstream connections, you can specify stats
	// matcher as follow:
	// ```yaml
	// proxyStatsMatcher:
	//   inclusionRegexps:
	//     - .*circuit_breakers.*
	//   inclusionPrefixes:
	//     - upstream_rq_retry
	//     - upstream_cx
	// ```
	// Note including more Envoy stats might increase number of time series
	// collected by prometheus significantly. Care needs to be taken on Prometheus
	// resource provision and configuration to reduce cardinality.
	ProxyStatsMatcher *ProxyConfig_ProxyStatsMatcher `protobuf:"bytes,32,opt,name=proxy_stats_matcher,json=proxyStatsMatcher,proto3" json:"proxyStatsMatcher,omitempty"`
	// Boolean flag for enabling/disabling the holdApplicationUntilProxyStarts behavior.
	// This feature adds hooks to delay application startup until the pod proxy
	// is ready to accept traffic, mitigating some startup race conditions.
	// Default value is 'false'.
	HoldApplicationUntilProxyStarts *wrappers.BoolValue `protobuf:"bytes,33,opt,name=hold_application_until_proxy_starts,json=holdApplicationUntilProxyStarts,proto3" json:"holdApplicationUntilProxyStarts,omitempty"`
	// The PEM data of the extra root certificates for workload-to-workload communication.
	// This includes the certificates defined in MeshConfig and any other certificates that Istiod uses as CA.
	// The plugin certificates (the 'cacerts' secret), self-signed certificates (the 'istio-ca-secret' secret)
	// are added automatically by Istiod.
	CaCertificatesPem    []string `protobuf:"bytes,34,rep,name=ca_certificates_pem,json=caCertificatesPem,proto3" json:"caCertificatesPem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyConfig) Reset()         { *m = ProxyConfig{} }
func (m *ProxyConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig) ProtoMessage()    {}
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{3}
}

func (m *ProxyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig.Unmarshal(m, b)
}
func (m *ProxyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig.Marshal(b, m, deterministic)
}
func (m *ProxyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig.Merge(m, src)
}
func (m *ProxyConfig) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig.Size(m)
}
func (m *ProxyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig proto.InternalMessageInfo

func (m *ProxyConfig) GetConfigPath() string {
	if m != nil {
		return m.ConfigPath
	}
	return ""
}

func (m *ProxyConfig) GetBinaryPath() string {
	if m != nil {
		return m.BinaryPath
	}
	return ""
}

func (m *ProxyConfig) GetServiceCluster() string {
	if m != nil {
		return m.ServiceCluster
	}
	return ""
}

func (m *ProxyConfig) GetDrainDuration() *duration.Duration {
	if m != nil {
		return m.DrainDuration
	}
	return nil
}

func (m *ProxyConfig) GetParentShutdownDuration() *duration.Duration {
	if m != nil {
		return m.ParentShutdownDuration
	}
	return nil
}

func (m *ProxyConfig) GetDiscoveryAddress() string {
	if m != nil {
		return m.DiscoveryAddress
	}
	return ""
}

// Deprecated: Do not use.
func (m *ProxyConfig) GetDiscoveryRefreshDelay() *duration.Duration {
	if m != nil {
		return m.DiscoveryRefreshDelay
	}
	return nil
}

// Deprecated: Do not use.
func (m *ProxyConfig) GetZipkinAddress() string {
	if m != nil {
		return m.ZipkinAddress
	}
	return ""
}

func (m *ProxyConfig) GetStatsdUdpAddress() string {
	if m != nil {
		return m.StatsdUdpAddress
	}
	return ""
}

// Deprecated: Do not use.
func (m *ProxyConfig) GetEnvoyMetricsServiceAddress() string {
	if m != nil {
		return m.EnvoyMetricsServiceAddress
	}
	return ""
}

func (m *ProxyConfig) GetProxyAdminPort() int32 {
	if m != nil {
		return m.ProxyAdminPort
	}
	return 0
}

// Deprecated: Do not use.
func (m *ProxyConfig) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

func (m *ProxyConfig) GetControlPlaneAuthPolicy() AuthenticationPolicy {
	if m != nil {
		return m.ControlPlaneAuthPolicy
	}
	return AuthenticationPolicy_NONE
}

func (m *ProxyConfig) GetCustomConfigFile() string {
	if m != nil {
		return m.CustomConfigFile
	}
	return ""
}

func (m *ProxyConfig) GetStatNameLength() int32 {
	if m != nil {
		return m.StatNameLength
	}
	return 0
}

func (m *ProxyConfig) GetConcurrency() *wrappers.Int32Value {
	if m != nil {
		return m.Concurrency
	}
	return nil
}

func (m *ProxyConfig) GetProxyBootstrapTemplatePath() string {
	if m != nil {
		return m.ProxyBootstrapTemplatePath
	}
	return ""
}

func (m *ProxyConfig) GetInterceptionMode() ProxyConfig_InboundInterceptionMode {
	if m != nil {
		return m.InterceptionMode
	}
	return ProxyConfig_REDIRECT
}

func (m *ProxyConfig) GetTracing() *Tracing {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *ProxyConfig) GetSds() *SDS {
	if m != nil {
		return m.Sds
	}
	return nil
}

func (m *ProxyConfig) GetEnvoyAccessLogService() *RemoteService {
	if m != nil {
		return m.EnvoyAccessLogService
	}
	return nil
}

func (m *ProxyConfig) GetEnvoyMetricsService() *RemoteService {
	if m != nil {
		return m.EnvoyMetricsService
	}
	return nil
}

func (m *ProxyConfig) GetProxyMetadata() map[string]string {
	if m != nil {
		return m.ProxyMetadata
	}
	return nil
}

func (m *ProxyConfig) GetStatusPort() int32 {
	if m != nil {
		return m.StatusPort
	}
	return 0
}

func (m *ProxyConfig) GetExtraStatTags() []string {
	if m != nil {
		return m.ExtraStatTags
	}
	return nil
}

func (m *ProxyConfig) GetGatewayTopology() *Topology {
	if m != nil {
		return m.GatewayTopology
	}
	return nil
}

func (m *ProxyConfig) GetTerminationDrainDuration() *duration.Duration {
	if m != nil {
		return m.TerminationDrainDuration
	}
	return nil
}

func (m *ProxyConfig) GetMeshId() string {
	if m != nil {
		return m.MeshId
	}
	return ""
}

func (m *ProxyConfig) GetReadinessProbe() *v1alpha3.ReadinessProbe {
	if m != nil {
		return m.ReadinessProbe
	}
	return nil
}

func (m *ProxyConfig) GetProxyStatsMatcher() *ProxyConfig_ProxyStatsMatcher {
	if m != nil {
		return m.ProxyStatsMatcher
	}
	return nil
}

func (m *ProxyConfig) GetHoldApplicationUntilProxyStarts() *wrappers.BoolValue {
	if m != nil {
		return m.HoldApplicationUntilProxyStarts
	}
	return nil
}

func (m *ProxyConfig) GetCaCertificatesPem() []string {
	if m != nil {
		return m.CaCertificatesPem
	}
	return nil
}

// Proxy stats name matchers for stats creation. Note this is in addition to
// the minimum Envoy stats that Istio generates by default.
type ProxyConfig_ProxyStatsMatcher struct {
	// Proxy stats name prefix matcher for inclusion.
	InclusionPrefixes []string `protobuf:"bytes,1,rep,name=inclusion_prefixes,json=inclusionPrefixes,proto3" json:"inclusionPrefixes,omitempty"`
	// Proxy stats name suffix matcher for inclusion.
	InclusionSuffixes []string `protobuf:"bytes,2,rep,name=inclusion_suffixes,json=inclusionSuffixes,proto3" json:"inclusionSuffixes,omitempty"`
	// Proxy stats name regexps matcher for inclusion.
	InclusionRegexps     []string `protobuf:"bytes,3,rep,name=inclusion_regexps,json=inclusionRegexps,proto3" json:"inclusionRegexps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyConfig_ProxyStatsMatcher) Reset()         { *m = ProxyConfig_ProxyStatsMatcher{} }
func (m *ProxyConfig_ProxyStatsMatcher) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig_ProxyStatsMatcher) ProtoMessage()    {}
func (*ProxyConfig_ProxyStatsMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{3, 1}
}

func (m *ProxyConfig_ProxyStatsMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig_ProxyStatsMatcher.Unmarshal(m, b)
}
func (m *ProxyConfig_ProxyStatsMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig_ProxyStatsMatcher.Marshal(b, m, deterministic)
}
func (m *ProxyConfig_ProxyStatsMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig_ProxyStatsMatcher.Merge(m, src)
}
func (m *ProxyConfig_ProxyStatsMatcher) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig_ProxyStatsMatcher.Size(m)
}
func (m *ProxyConfig_ProxyStatsMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig_ProxyStatsMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig_ProxyStatsMatcher proto.InternalMessageInfo

func (m *ProxyConfig_ProxyStatsMatcher) GetInclusionPrefixes() []string {
	if m != nil {
		return m.InclusionPrefixes
	}
	return nil
}

func (m *ProxyConfig_ProxyStatsMatcher) GetInclusionSuffixes() []string {
	if m != nil {
		return m.InclusionSuffixes
	}
	return nil
}

func (m *ProxyConfig_ProxyStatsMatcher) GetInclusionRegexps() []string {
	if m != nil {
		return m.InclusionRegexps
	}
	return nil
}

type RemoteService struct {
	// Address of a remove service used for various purposes (access log
	// receiver, metrics receiver, etc.). Can be IP address or a fully
	// qualified DNS name.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Use the `tls_settings` to specify the tls mode to use. If the remote service
	// uses Istio mutual TLS and shares the root CA with Pilot, specify the TLS
	// mode as `ISTIO_MUTUAL`.
	TlsSettings *v1alpha3.ClientTLSSettings `protobuf:"bytes,2,opt,name=tls_settings,json=tlsSettings,proto3" json:"tlsSettings,omitempty"`
	// If set then set `SO_KEEPALIVE` on the socket to enable TCP Keepalives.
	TcpKeepalive         *v1alpha3.ConnectionPoolSettings_TCPSettings_TcpKeepalive `protobuf:"bytes,3,opt,name=tcp_keepalive,json=tcpKeepalive,proto3" json:"tcpKeepalive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *RemoteService) Reset()         { *m = RemoteService{} }
func (m *RemoteService) String() string { return proto.CompactTextString(m) }
func (*RemoteService) ProtoMessage()    {}
func (*RemoteService) Descriptor() ([]byte, []int) {
	return fileDescriptor_5efecd978cf3d28d, []int{4}
}

func (m *RemoteService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteService.Unmarshal(m, b)
}
func (m *RemoteService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteService.Marshal(b, m, deterministic)
}
func (m *RemoteService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteService.Merge(m, src)
}
func (m *RemoteService) XXX_Size() int {
	return xxx_messageInfo_RemoteService.Size(m)
}
func (m *RemoteService) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteService.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteService proto.InternalMessageInfo

func (m *RemoteService) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RemoteService) GetTlsSettings() *v1alpha3.ClientTLSSettings {
	if m != nil {
		return m.TlsSettings
	}
	return nil
}

func (m *RemoteService) GetTcpKeepalive() *v1alpha3.ConnectionPoolSettings_TCPSettings_TcpKeepalive {
	if m != nil {
		return m.TcpKeepalive
	}
	return nil
}

func init() {
	proto.RegisterEnum("istio.mesh.v1alpha1.AuthenticationPolicy", AuthenticationPolicy_name, AuthenticationPolicy_value)
	proto.RegisterEnum("istio.mesh.v1alpha1.Tracing_OpenCensusAgent_TraceContext", Tracing_OpenCensusAgent_TraceContext_name, Tracing_OpenCensusAgent_TraceContext_value)
	proto.RegisterEnum("istio.mesh.v1alpha1.Topology_ForwardClientCertDetails", Topology_ForwardClientCertDetails_name, Topology_ForwardClientCertDetails_value)
	proto.RegisterEnum("istio.mesh.v1alpha1.ProxyConfig_InboundInterceptionMode", ProxyConfig_InboundInterceptionMode_name, ProxyConfig_InboundInterceptionMode_value)
	proto.RegisterType((*Tracing)(nil), "istio.mesh.v1alpha1.Tracing")
	proto.RegisterMapType((map[string]*Tracing_CustomTag)(nil), "istio.mesh.v1alpha1.Tracing.CustomTagsEntry")
	proto.RegisterType((*Tracing_Zipkin)(nil), "istio.mesh.v1alpha1.Tracing.Zipkin")
	proto.RegisterType((*Tracing_Lightstep)(nil), "istio.mesh.v1alpha1.Tracing.Lightstep")
	proto.RegisterType((*Tracing_Datadog)(nil), "istio.mesh.v1alpha1.Tracing.Datadog")
	proto.RegisterType((*Tracing_Stackdriver)(nil), "istio.mesh.v1alpha1.Tracing.Stackdriver")
	proto.RegisterType((*Tracing_OpenCensusAgent)(nil), "istio.mesh.v1alpha1.Tracing.OpenCensusAgent")
	proto.RegisterType((*Tracing_CustomTag)(nil), "istio.mesh.v1alpha1.Tracing.CustomTag")
	proto.RegisterType((*Tracing_Literal)(nil), "istio.mesh.v1alpha1.Tracing.Literal")
	proto.RegisterType((*Tracing_Environment)(nil), "istio.mesh.v1alpha1.Tracing.Environment")
	proto.RegisterType((*Tracing_RequestHeader)(nil), "istio.mesh.v1alpha1.Tracing.RequestHeader")
	proto.RegisterType((*SDS)(nil), "istio.mesh.v1alpha1.SDS")
	proto.RegisterType((*Topology)(nil), "istio.mesh.v1alpha1.Topology")
	proto.RegisterType((*ProxyConfig)(nil), "istio.mesh.v1alpha1.ProxyConfig")
	proto.RegisterMapType((map[string]string)(nil), "istio.mesh.v1alpha1.ProxyConfig.ProxyMetadataEntry")
	proto.RegisterType((*ProxyConfig_ProxyStatsMatcher)(nil), "istio.mesh.v1alpha1.ProxyConfig.ProxyStatsMatcher")
	proto.RegisterType((*RemoteService)(nil), "istio.mesh.v1alpha1.RemoteService")
}

func init() {
	proto.RegisterFile("mesh/v1alpha1/proxy.proto", fileDescriptor_5efecd978cf3d28d)
}

var fileDescriptor_5efecd978cf3d28d = []byte{
	// 2149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xdd, 0x52, 0x1b, 0xc9,
	0x15, 0x46, 0x02, 0x03, 0x3a, 0xfc, 0x0d, 0x8d, 0xb1, 0xc7, 0x5a, 0x7b, 0xcd, 0xe2, 0xcd, 0x86,
	0x75, 0x76, 0x45, 0xad, 0x49, 0x6d, 0x39, 0xa9, 0x6c, 0x6a, 0x85, 0x24, 0x82, 0x1c, 0x10, 0xaa,
	0x91, 0xb0, 0xd7, 0xec, 0x45, 0x57, 0x6b, 0xa6, 0x25, 0x4d, 0x98, 0xe9, 0x9e, 0x74, 0xf7, 0x00,
	0xda, 0x27, 0xc8, 0x53, 0xe4, 0x2e, 0xb7, 0xa9, 0x3c, 0x40, 0xde, 0x27, 0x49, 0xe5, 0x25, 0x52,
	0xdd, 0x3d, 0x23, 0x04, 0xc6, 0xb2, 0x93, 0xdc, 0xa9, 0xcf, 0xf9, 0xbe, 0x6f, 0xfa, 0xe7, 0x9c,
	0xd3, 0xa7, 0x05, 0x8f, 0x62, 0x2a, 0x87, 0xbb, 0x17, 0xdf, 0x90, 0x28, 0x19, 0x92, 0x6f, 0x76,
	0x13, 0xc1, 0xaf, 0x46, 0x95, 0x44, 0x70, 0xc5, 0xd1, 0x46, 0x28, 0x55, 0xc8, 0x2b, 0x1a, 0x50,
	0xc9, 0x01, 0xe5, 0x4f, 0x07, 0x9c, 0x0f, 0x22, 0xba, 0x6b, 0x20, 0xbd, 0xb4, 0xbf, 0x1b, 0xa4,
	0x82, 0xa8, 0x90, 0x33, 0x4b, 0x7a, 0xd7, 0x7f, 0x29, 0x48, 0x92, 0x50, 0x21, 0x33, 0xff, 0x73,
	0x46, 0xd5, 0x25, 0x17, 0xe7, 0x21, 0x1b, 0xe4, 0x5f, 0xdd, 0xdb, 0x0d, 0xa8, 0x54, 0x21, 0x33,
	0x32, 0x58, 0xa4, 0x11, 0xcd, 0xb0, 0x3b, 0x77, 0x61, 0xb5, 0x21, 0xe2, 0x24, 0xc0, 0x03, 0xc1,
	0xd3, 0xc4, 0x22, 0xb7, 0xff, 0xb2, 0x0a, 0x0b, 0x5d, 0x41, 0xfc, 0x90, 0x0d, 0xd0, 0x77, 0x30,
	0xff, 0x53, 0x98, 0x9c, 0x87, 0xcc, 0x2d, 0x6c, 0x15, 0x76, 0x96, 0x5e, 0x3c, 0xab, 0xdc, 0xb1,
	0x8e, 0x4a, 0x86, 0xae, 0x9c, 0x19, 0xe8, 0xe1, 0x8c, 0x97, 0x91, 0xd0, 0x01, 0x94, 0xa2, 0x70,
	0x30, 0x54, 0x52, 0xd1, 0xc4, 0x2d, 0x1a, 0x85, 0x2f, 0xa6, 0x2a, 0x1c, 0xe5, 0xe8, 0xc3, 0x19,
	0xef, 0x9a, 0x8a, 0xbe, 0x87, 0x85, 0x80, 0x28, 0x12, 0xf0, 0x81, 0x3b, 0x6b, 0x54, 0x3e, 0x9f,
	0xaa, 0x52, 0xb7, 0xd8, 0xc3, 0x19, 0x2f, 0xa7, 0xa1, 0x23, 0x58, 0x92, 0x8a, 0xf8, 0xe7, 0x81,
	0x08, 0x2f, 0xa8, 0x70, 0xe7, 0x8c, 0xca, 0xce, 0x54, 0x95, 0xce, 0x35, 0xfe, 0x70, 0xc6, 0x9b,
	0xa4, 0xa3, 0x33, 0x58, 0xe7, 0x09, 0x65, 0xd8, 0xa7, 0x4c, 0xa6, 0x12, 0x93, 0x01, 0x65, 0xca,
	0x2d, 0x19, 0xcd, 0xaf, 0xa6, 0x6a, 0x9e, 0x24, 0x94, 0xd5, 0x0c, 0xa9, 0xaa, 0x39, 0x87, 0x33,
	0xde, 0x1a, 0xbf, 0x69, 0x42, 0xc7, 0xb0, 0xe4, 0xa7, 0x52, 0xf1, 0x18, 0x2b, 0x32, 0x90, 0xee,
	0xbd, 0xad, 0xd9, 0x0f, 0xaa, 0xd6, 0x0c, 0xbe, 0x4b, 0x06, 0xb2, 0xc1, 0x94, 0x18, 0x79, 0xe0,
	0x8f, 0x0d, 0xe8, 0x6b, 0xd8, 0x88, 0xc9, 0x15, 0x4e, 0x88, 0x1a, 0x6a, 0x41, 0x1c, 0x51, 0x36,
	0x50, 0x43, 0x77, 0x7e, 0xab, 0xb0, 0xb3, 0xe2, 0x39, 0x31, 0xb9, 0x6a, 0x13, 0x35, 0xec, 0x92,
	0xc1, 0x91, 0xb1, 0xa3, 0x32, 0x2c, 0x4a, 0x12, 0x27, 0x51, 0xc8, 0x06, 0xee, 0xc2, 0x56, 0x61,
	0xa7, 0xe0, 0x8d, 0xc7, 0xe8, 0x04, 0x96, 0x55, 0x24, 0xb1, 0xa4, 0x4a, 0x85, 0x6c, 0x20, 0xdd,
	0xc5, 0x1b, 0x0b, 0xbe, 0x8e, 0xaf, 0x7c, 0x82, 0x7b, 0x95, 0x5a, 0x14, 0x52, 0xa6, 0xba, 0x47,
	0x9d, 0x4e, 0xc6, 0xf1, 0x96, 0x54, 0x24, 0xf3, 0x41, 0x79, 0x1b, 0xe6, 0x6d, 0xc8, 0x20, 0x17,
	0x16, 0x48, 0x10, 0x08, 0x2a, 0xa5, 0x09, 0xb4, 0x92, 0x97, 0x0f, 0xcb, 0x87, 0x50, 0x1a, 0x07,
	0xc5, 0xfb, 0x61, 0xe8, 0x33, 0x58, 0x26, 0xbe, 0x4f, 0xa5, 0xc4, 0x8a, 0x9f, 0x53, 0x66, 0x82,
	0xad, 0xe4, 0x2d, 0x59, 0x5b, 0x57, 0x9b, 0xca, 0xcf, 0x60, 0x21, 0x0b, 0x8c, 0x29, 0x9f, 0xfb,
	0x6b, 0x11, 0x96, 0x26, 0x0e, 0x1e, 0xdd, 0x87, 0x7b, 0x01, 0xed, 0xa5, 0x03, 0x83, 0x5b, 0xf4,
	0xec, 0x00, 0x75, 0xc1, 0xd5, 0x9b, 0xca, 0xd2, 0xb8, 0x47, 0x05, 0xe6, 0x7d, 0x4c, 0x94, 0x12,
	0x61, 0x2f, 0x55, 0x54, 0x66, 0x61, 0xfe, 0x49, 0xc5, 0xe6, 0x6e, 0x25, 0xcf, 0xdd, 0x4a, 0x93,
	0xa9, 0x6f, 0x7f, 0xf9, 0x9a, 0x44, 0x29, 0xf5, 0x36, 0x63, 0x72, 0xd5, 0x32, 0xdc, 0x93, 0x7e,
	0x75, 0xcc, 0x44, 0xaf, 0xe1, 0xd1, 0x2d, 0x55, 0xc6, 0xb8, 0x32, 0x99, 0x2c, 0xb3, 0xb8, 0x9f,
	0x2a, 0xfb, 0x60, 0x52, 0xf6, 0x9a, 0x8a, 0x7e, 0x84, 0xc7, 0x37, 0x75, 0x63, 0x2a, 0x25, 0x19,
	0x50, 0x4c, 0x2f, 0x28, 0x53, 0x32, 0x4b, 0x86, 0xa9, 0xd2, 0xee, 0x84, 0xf4, 0xb1, 0x65, 0x37,
	0x0c, 0xb9, 0xfc, 0x8f, 0x02, 0xac, 0xdd, 0x8a, 0xea, 0x29, 0xc7, 0xd4, 0x81, 0x05, 0x9f, 0x33,
	0x45, 0xaf, 0x94, 0x5b, 0xdc, 0x9a, 0xdd, 0x59, 0x7d, 0xf1, 0xab, 0xff, 0x26, 0x5d, 0x8c, 0x9d,
	0xd6, 0xac, 0x80, 0x97, 0x2b, 0x6d, 0x53, 0x58, 0x9e, 0x74, 0xa0, 0x35, 0x58, 0x3a, 0x6d, 0x75,
	0xda, 0x8d, 0x5a, 0xf3, 0xa0, 0xd9, 0xa8, 0x3b, 0x33, 0x68, 0x13, 0xd6, 0xdf, 0xec, 0xd5, 0x70,
	0xd7, 0xab, 0xd6, 0x1a, 0xb8, 0x76, 0xd2, 0xea, 0x36, 0x7e, 0xe8, 0x3a, 0x05, 0xb4, 0x0c, 0x8b,
	0xbf, 0xf3, 0xda, 0x35, 0xbc, 0xdf, 0x6c, 0x39, 0x45, 0xf4, 0x10, 0x36, 0x6a, 0x47, 0x27, 0xa7,
	0xf5, 0x5b, 0xb0, 0x59, 0x34, 0x0f, 0xc5, 0xfd, 0x3d, 0x67, 0xae, 0xfc, 0xaf, 0x02, 0x94, 0xc6,
	0x99, 0xa6, 0x4b, 0x52, 0x14, 0x2a, 0x2a, 0x48, 0x94, 0x95, 0xc6, 0xcf, 0x3f, 0x50, 0xd8, 0x0c,
	0x56, 0x97, 0xa4, 0x8c, 0xa6, 0x4b, 0x12, 0x65, 0x17, 0xa1, 0xe0, 0x2c, 0xd6, 0xe5, 0xa3, 0xf8,
	0x11, 0x25, 0xa9, 0x71, 0x8d, 0xd7, 0x25, 0x69, 0x82, 0x8e, 0xea, 0x30, 0x3f, 0xa4, 0x24, 0xa0,
	0x22, 0x8b, 0x94, 0xe7, 0x53, 0x85, 0x3c, 0xfa, 0xc7, 0x94, 0x4a, 0x75, 0x68, 0x18, 0xba, 0x60,
	0x5b, 0xee, 0xfe, 0x3c, 0xcc, 0xa9, 0x51, 0x42, 0xcb, 0x4f, 0x61, 0x21, 0x9b, 0xb1, 0xce, 0x80,
	0x0b, 0x1d, 0x03, 0xd9, 0x51, 0xda, 0x41, 0xf9, 0x00, 0x96, 0x26, 0x26, 0x83, 0x10, 0xcc, 0x31,
	0x12, 0xe7, 0x18, 0xf3, 0x1b, 0x3d, 0x83, 0x95, 0x80, 0xf6, 0x49, 0x1a, 0x29, 0x6c, 0x05, 0x6c,
	0x4e, 0x2e, 0x67, 0x46, 0x13, 0x58, 0xe5, 0x43, 0x58, 0xb9, 0x31, 0x97, 0xff, 0x5d, 0x89, 0xc2,
	0xda, 0xad, 0x3a, 0x88, 0x1c, 0x98, 0x3d, 0xa7, 0xa3, 0x4c, 0x4a, 0xff, 0x44, 0xbf, 0xc9, 0x17,
	0xf3, 0x31, 0x97, 0xd1, 0x58, 0x2e, 0x5b, 0xf4, 0xaf, 0x8b, 0x2f, 0x0b, 0xfb, 0x8b, 0x30, 0xaf,
	0x74, 0xb0, 0x89, 0xed, 0x03, 0x98, 0xed, 0xd4, 0x3b, 0x3a, 0xd8, 0x29, 0x23, 0xbd, 0x88, 0x06,
	0x59, 0x8d, 0xc8, 0x87, 0xe8, 0x67, 0xb0, 0x76, 0xfe, 0x52, 0x62, 0x49, 0xf0, 0x1f, 0x2e, 0x95,
	0xa9, 0xc0, 0xf9, 0xc4, 0xcf, 0x5f, 0xca, 0x0e, 0x79, 0x75, 0xa9, 0x74, 0xed, 0xdd, 0xfe, 0x7b,
	0x11, 0x16, 0xbb, 0x3c, 0xe1, 0x11, 0x1f, 0x8c, 0x50, 0x05, 0x36, 0x58, 0x1a, 0x63, 0x25, 0x52,
	0xa9, 0x68, 0x80, 0x75, 0x0b, 0x11, 0x52, 0x9b, 0x46, 0x2b, 0xde, 0x3a, 0x4b, 0xe3, 0xae, 0xf5,
	0xb4, 0xad, 0x03, 0xa5, 0xf0, 0x49, 0x9f, 0x8b, 0x4b, 0x22, 0x02, 0xec, 0x9b, 0x62, 0x8b, 0x7d,
	0x2a, 0x14, 0x0e, 0xa8, 0x22, 0x61, 0x64, 0x8b, 0xd1, 0xea, 0x8b, 0x6f, 0xef, 0x5e, 0x66, 0xf6,
	0xcd, 0xca, 0x81, 0x15, 0xb0, 0xc5, 0xba, 0x46, 0x85, 0xaa, 0x5b, 0xb6, 0xe7, 0xf6, 0xdf, 0xe3,
	0xd9, 0xfe, 0x53, 0x01, 0xdc, 0xf7, 0xd1, 0xd0, 0x0a, 0x94, 0x4e, 0x5b, 0xf5, 0xc6, 0x41, 0xb3,
	0x65, 0xb2, 0x6f, 0x19, 0x16, 0x3b, 0xd5, 0x56, 0xb3, 0xdb, 0x3c, 0x6b, 0x38, 0x05, 0xe4, 0xc0,
	0xf2, 0xc1, 0x89, 0xf7, 0xa6, 0xea, 0xd5, 0xf1, 0x49, 0xeb, 0xe8, 0xad, 0x53, 0x44, 0x08, 0x56,
	0xab, 0xed, 0x76, 0xa3, 0x55, 0xc7, 0x99, 0xc3, 0x99, 0xd5, 0xa8, 0x9c, 0x83, 0x3b, 0x8d, 0xae,
	0x33, 0xa7, 0xd3, 0xb3, 0x7a, 0xf4, 0xa6, 0xfa, 0xb6, 0x83, 0x6f, 0xd0, 0xef, 0x6d, 0xff, 0x0d,
	0xc1, 0x92, 0xde, 0x8d, 0x51, 0x8d, 0xb3, 0x7e, 0x38, 0x40, 0x4f, 0x61, 0xc9, 0x37, 0xbf, 0xec,
	0x8e, 0xdb, 0xc3, 0x07, 0x6b, 0xd2, 0xfb, 0xad, 0x01, 0xbd, 0x90, 0x11, 0x31, 0x9a, 0x3c, 0x12,
	0xb0, 0x26, 0x03, 0xf8, 0x39, 0xac, 0x49, 0x2a, 0x2e, 0x42, 0x9f, 0x62, 0x3f, 0xd2, 0xbb, 0x6d,
	0x73, 0xaa, 0xe4, 0xad, 0x66, 0xe6, 0x9a, 0xb5, 0xa2, 0xef, 0x61, 0x35, 0x10, 0x24, 0x64, 0x38,
	0xef, 0xdb, 0xb2, 0x52, 0xfa, 0xe8, 0x9d, 0x52, 0x5a, 0xcf, 0x00, 0xde, 0x8a, 0x21, 0xe4, 0x43,
	0xd4, 0x01, 0x37, 0x21, 0x42, 0x1f, 0x9b, 0x1c, 0xa6, 0x2a, 0xe0, 0x97, 0x13, 0x5a, 0xf7, 0x3e,
	0xa4, 0xf5, 0xc0, 0x52, 0x3b, 0x19, 0x73, 0x2c, 0xfa, 0x0b, 0x58, 0x0f, 0x42, 0xe9, 0xf3, 0x0b,
	0x2a, 0x46, 0x38, 0x2f, 0xc4, 0xf3, 0x66, 0x05, 0xce, 0xd8, 0x51, 0xcd, 0x2a, 0xf2, 0x29, 0x3c,
	0xbc, 0x06, 0x0b, 0xda, 0x17, 0x54, 0x0e, 0x71, 0x40, 0x23, 0x32, 0x32, 0xf7, 0xff, 0xb4, 0x09,
	0xec, 0x17, 0xdd, 0x82, 0xb7, 0x39, 0x66, 0x7b, 0x96, 0x5c, 0xd7, 0x5c, 0xf4, 0x25, 0xac, 0xda,
	0x1e, 0x70, 0x3c, 0x01, 0xdd, 0x2d, 0x94, 0x0c, 0x65, 0xc5, 0x7a, 0xf2, 0x19, 0x7c, 0x05, 0x48,
	0x2a, 0xa2, 0x64, 0x80, 0xd3, 0x20, 0x19, 0xc3, 0xc1, 0xce, 0xd7, 0x7a, 0x4e, 0x83, 0x24, 0x47,
	0x37, 0xe0, 0x09, 0x65, 0x17, 0x7c, 0x84, 0x63, 0xaa, 0x44, 0xe8, 0xeb, 0x76, 0xc4, 0x1e, 0x55,
	0x4e, 0xbc, 0x3f, 0xfe, 0x4e, 0xd9, 0x00, 0x8f, 0x2d, 0xae, 0x63, 0x61, 0xb9, 0xcc, 0x0e, 0x38,
	0xa6, 0x3d, 0xc7, 0x24, 0x88, 0x43, 0x86, 0x13, 0x2e, 0x94, 0xbb, 0xb4, 0x55, 0xd8, 0xb9, 0xe7,
	0xad, 0x1a, 0x7b, 0x55, 0x9b, 0xdb, 0x5c, 0x28, 0xb4, 0x0b, 0xeb, 0xe4, 0x82, 0x84, 0x11, 0xe9,
	0x85, 0x51, 0xa8, 0x46, 0xf8, 0x27, 0xce, 0xa8, 0xbb, 0x3c, 0xfe, 0x88, 0x33, 0xe9, 0x3c, 0xe3,
	0x8c, 0xa2, 0x00, 0x1e, 0xe9, 0x9b, 0x49, 0xf0, 0x08, 0x27, 0x11, 0x61, 0x14, 0x93, 0x54, 0x0d,
	0x71, 0xc2, 0xa3, 0xd0, 0x1f, 0xb9, 0x2b, 0x26, 0x21, 0xbf, 0xbc, 0x33, 0x21, 0xab, 0xa9, 0x1a,
	0x52, 0xa6, 0x42, 0xdf, 0xec, 0x6e, 0xdb, 0x10, 0xbc, 0x07, 0x99, 0x56, 0x5b, 0x4b, 0x69, 0x84,
	0xb5, 0xeb, 0x5d, 0xcb, 0xda, 0xc4, 0x2c, 0xda, 0xfb, 0x61, 0x44, 0xdd, 0x55, 0xbb, 0x6b, 0xd6,
	0x63, 0x13, 0xe2, 0x20, 0x8c, 0xa8, 0x5e, 0xae, 0xde, 0x49, 0xac, 0xcb, 0x69, 0xde, 0x02, 0xae,
	0xd9, 0xe5, 0x6a, 0x7b, 0x8b, 0xc4, 0x34, 0x6b, 0x00, 0xbf, 0x33, 0xe9, 0xe3, 0xa7, 0x42, 0x50,
	0xe6, 0x8f, 0x5c, 0xe7, 0xfd, 0xbd, 0xc1, 0xde, 0x0b, 0xdb, 0x1b, 0x4c, 0xe2, 0x51, 0x15, 0x9e,
	0xd8, 0x7d, 0xed, 0x71, 0xae, 0xa4, 0x12, 0x24, 0xc1, 0x8a, 0xc6, 0x49, 0x44, 0x14, 0xb5, 0xe9,
	0xb6, 0x6e, 0x66, 0x58, 0x36, 0xa0, 0xfd, 0x1c, 0xd3, 0xcd, 0x20, 0x26, 0xfd, 0x28, 0xac, 0x87,
	0x4c, 0x51, 0xe1, 0xd3, 0xc4, 0x3c, 0x62, 0x62, 0x1e, 0x50, 0x17, 0x99, 0x7d, 0x7b, 0x79, 0xe7,
	0xbe, 0x4d, 0x64, 0x7f, 0xa5, 0xc9, 0x7a, 0x3c, 0x65, 0x41, 0x73, 0x42, 0xe0, 0x98, 0x07, 0xd4,
	0x73, 0xc2, 0x5b, 0x16, 0xf4, 0x2d, 0x2c, 0x28, 0x5b, 0xe8, 0xdd, 0x0d, 0xb3, 0xc8, 0xc7, 0xd3,
	0x2e, 0x03, 0x2f, 0x07, 0xa3, 0xe7, 0x30, 0x2b, 0x03, 0xe9, 0x6e, 0x1a, 0x8e, 0x7b, 0x27, 0xa7,
	0x53, 0xef, 0x78, 0x1a, 0x84, 0x7e, 0x04, 0xd7, 0x06, 0x6b, 0xd6, 0x9b, 0x46, 0x7c, 0x90, 0xc7,
	0xab, 0xfb, 0xc0, 0x08, 0x6c, 0xdf, 0x29, 0xe0, 0xd1, 0x98, 0x2b, 0x9a, 0x85, 0xac, 0xb7, 0x69,
	0x34, 0xaa, 0x46, 0xe2, 0x88, 0x0f, 0x32, 0x33, 0x7a, 0x0d, 0x9b, 0x77, 0x66, 0x82, 0xfb, 0xf0,
	0xa3, 0x95, 0x37, 0xee, 0xc8, 0x10, 0x74, 0x06, 0x36, 0x05, 0xb4, 0x2e, 0xd1, 0xef, 0x27, 0xd7,
	0x35, 0x6f, 0x90, 0xbd, 0x0f, 0x6e, 0xbe, 0xf9, 0x7d, 0x9c, 0xb1, 0xec, 0x53, 0x64, 0x25, 0x99,
	0xb4, 0xe9, 0xda, 0xab, 0xe3, 0x2d, 0x95, 0x36, 0xe3, 0xca, 0x26, 0x04, 0xc1, 0x9a, 0x4c, 0xb6,
	0x7d, 0x01, 0x6b, 0xf4, 0x4a, 0x09, 0x82, 0x4d, 0xb8, 0x9a, 0x17, 0xd0, 0x27, 0x5b, 0xb3, 0x3b,
	0x25, 0x6f, 0xc5, 0x98, 0x3b, 0x8a, 0x28, 0xf3, 0xac, 0x39, 0x04, 0x67, 0x40, 0x14, 0xbd, 0x24,
	0x23, 0xac, 0xb2, 0x7b, 0xcc, 0x7d, 0x6c, 0xd6, 0xfd, 0x64, 0xea, 0x65, 0xe7, 0xad, 0x65, 0xb4,
	0xf1, 0x8d, 0xfb, 0x06, 0xca, 0x8a, 0x8a, 0x38, 0x7f, 0x32, 0xdf, 0x2a, 0xe8, 0x4f, 0x3e, 0x54,
	0x84, 0xdd, 0x09, 0x72, 0xfd, 0x46, 0x6d, 0x7f, 0x08, 0x0b, 0x7a, 0x0e, 0x38, 0x0c, 0xdc, 0x4f,
	0x4d, 0xd0, 0xcf, 0xeb, 0x61, 0x33, 0x40, 0x1e, 0xac, 0x09, 0x4a, 0x82, 0x90, 0xe9, 0x90, 0x48,
	0x04, 0xef, 0x51, 0xf7, 0xa9, 0xf9, 0xcc, 0x97, 0x53, 0x9e, 0x52, 0x5e, 0xce, 0x68, 0x6b, 0x82,
	0xb7, 0x2a, 0x6e, 0x8c, 0x51, 0x0f, 0x36, 0xec, 0xa1, 0x99, 0x82, 0x89, 0x63, 0xa2, 0xfc, 0x21,
	0x15, 0xee, 0x96, 0xd1, 0x7d, 0xf1, 0x71, 0x27, 0xa7, 0x37, 0x57, 0x1e, 0x5b, 0xa6, 0xb7, 0x9e,
	0xdc, 0x36, 0xa1, 0x21, 0x3c, 0x1b, 0xf2, 0x28, 0xc0, 0x24, 0x49, 0xa2, 0xac, 0x48, 0xe1, 0x94,
	0xa9, 0x30, 0xc2, 0xe3, 0x4f, 0x0b, 0x25, 0xdd, 0xcf, 0xcc, 0x37, 0xcb, 0xef, 0x6c, 0xd9, 0x3e,
	0xe7, 0x91, 0xad, 0x18, 0x4f, 0xb5, 0x4c, 0xf5, 0x5a, 0xe5, 0x54, 0x8b, 0xe4, 0x53, 0x10, 0x4a,
	0xea, 0x2e, 0xc8, 0x27, 0xa6, 0x93, 0x09, 0xfb, 0x1a, 0x43, 0x25, 0x4e, 0x68, 0xec, 0x6e, 0x9b,
	0x48, 0x58, 0xf7, 0x49, 0x6d, 0xc2, 0xd3, 0xa6, 0x71, 0xf9, 0x7b, 0x40, 0xef, 0xc6, 0xde, 0x1d,
	0xed, 0xdf, 0xfd, 0xc9, 0xf6, 0xaf, 0x34, 0xd1, 0xd6, 0x95, 0xff, 0x5c, 0x80, 0xf5, 0x77, 0x36,
	0x01, 0x7d, 0x0d, 0x28, 0x64, 0xba, 0x07, 0xd0, 0x4b, 0x4d, 0x04, 0xed, 0x87, 0x57, 0xa6, 0x19,
	0x33, 0xd3, 0x18, 0x7b, 0xda, 0x99, 0xe3, 0x26, 0x5c, 0xa6, 0x7d, 0x0b, 0x2f, 0xde, 0x82, 0x77,
	0x32, 0x87, 0xbe, 0xa7, 0xaf, 0xe1, 0x82, 0x0e, 0xe8, 0x55, 0xa2, 0xdf, 0x79, 0x1a, 0xed, 0x8c,
	0x1d, 0x9e, 0xb5, 0x6f, 0xef, 0xc1, 0xc3, 0xf7, 0xd4, 0x36, 0xdd, 0x60, 0x79, 0x8d, 0x7a, 0xd3,
	0x6b, 0xd4, 0xba, 0xce, 0x0c, 0x02, 0x98, 0xef, 0xb6, 0xbd, 0x93, 0x1f, 0xde, 0x3a, 0x85, 0x57,
	0x73, 0x8b, 0x25, 0x07, 0xbc, 0x35, 0x9f, 0x33, 0x46, 0x7d, 0x85, 0x55, 0x18, 0x53, 0x9e, 0xaa,
	0xed, 0x7f, 0x17, 0x74, 0xd7, 0x3d, 0x51, 0x08, 0xa6, 0xbc, 0xd8, 0x6e, 0x3f, 0xfa, 0x8b, 0xff,
	0xe7, 0xa3, 0x1f, 0x71, 0x58, 0x51, 0x7e, 0x82, 0xcf, 0x29, 0x4d, 0x48, 0x14, 0x5e, 0xd0, 0xec,
	0xbd, 0xf2, 0x6a, 0x9a, 0xa2, 0x9d, 0xbf, 0xb9, 0x14, 0x79, 0x94, 0x2b, 0x55, 0xba, 0xb5, 0xf6,
	0xf5, 0x6f, 0x3f, 0xf9, 0x7d, 0xae, 0xe8, 0x2d, 0xab, 0x89, 0xd1, 0xf3, 0xdf, 0xc2, 0xfd, 0xbb,
	0x6e, 0x56, 0xb4, 0x08, 0x73, 0xad, 0x93, 0x56, 0xc3, 0x99, 0x41, 0xab, 0x00, 0xc7, 0xa7, 0xdd,
	0xd3, 0xea, 0x11, 0xee, 0x1e, 0x75, 0xcc, 0xc3, 0x70, 0xa1, 0xd9, 0x3a, 0x6c, 0x78, 0xcd, 0xae,
	0xf3, 0xcf, 0x85, 0xfd, 0xc7, 0x67, 0x65, 0x3b, 0xb5, 0x90, 0xef, 0x92, 0x24, 0xdc, 0xbd, 0xf1,
	0x27, 0x5f, 0x6f, 0xde, 0xc4, 0xf7, 0xde, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x18, 0xca, 0x7e,
	0x16, 0xfc, 0x13, 0x00, 0x00,
}
